/**
 * The compilation projection of #12's `extension` external mapping.
 *
 * Decision source: GitHub Issue #12 — "Spec: `extension` dependencies as external
 * modules + `frontendLibraries` metadata"
 * (https://github.com/Mang-X/forguncy-react-workspace/issues/12), which is itself
 * downstream of:
 * - #4 "application ownership boundaries and dependency strategy semantics"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/4
 * - #5 "establish the ReactCellType target/runtime contract on Forguncy 12.0.100"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/5
 * - #6 "generated ReactCellType artifact and compiler boundary"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/6
 *
 * `core` owns *which* import a verified extension stands in for, what keeps that
 * mapping independent of library load order, and the diagnostic vocabulary. This
 * module owns what the compilation path does with that: the module handed to the
 * bundler in place of the dependency, and the externals plan a resolver hook is
 * wired from.
 *
 * Three things here are deliberate, and each is the answer to one of #12's
 * acceptance criteria:
 *
 * 1. **The interposition is keyed on the specifier and is a pure function of the
 *    mapping.** No function here takes authored source as an argument, so nothing
 *    can rewrite one (#12: "Compiler external mapping can preserve normal source
 *    imports") and there is no place for a package-specific AST rule to live.
 *    {@link planExtensionExternals} derives its set by walking the mapping table,
 *    so a new row is the whole of the change.
 * 2. **The generated module exports the page object itself, resolved while its own body
 *    runs, and reads no other extension's global.** Those two together make "no
 *    dependency on extension load order is introduced" a property of the emitted code
 *    rather than an argument about how a page happened to load things — see `core`'s
 *    `EXTENSION_LOAD_ORDER_RULES`, which this module implements, and
 *    `EXTENSION_EXTERNAL_INTEROP_BEHAVIOUR`, which is what rules out the two shapes a
 *    first design reaches for (a lazily-resolving proxy, and a narrowed view).
 * 3. **The library reference is derived, not assumed.** The plan reports the
 *    `frontendLibraries` metadata #6 canonicalizes from the same decisions, and
 *    reports an import the mapping intercepts but nothing declares, because that is
 *    the state in which the artifact reads a global no cell asked the page to load.
 *
 * Scope note: this module generates the interposed modules and plans the externals,
 * and audits a decision list against the mapping table. It does not drive a bundler,
 * assemble an artifact, or emit a diagnostic into #6's artifact report — wiring the
 * externals into the compile boundary is the compiler MVP's job (#7), exactly as
 * #9's bridge was left to it, and asserting an externals diagnostic through
 * `CellArtifactDiagnostic` would put two vocabularies in one report before anyone has
 * decided how they compose. It also does not package an extension; that is
 * `MangMax/forguncy-frontend-library`'s.
 */

import {
  assertExtensionExternalContract,
  auditExtensionLibraryMetadata,
  createExtensionExternalDiagnostic,
  extensionExternalDiagnosticRule,
  extensionInterceptedModuleIds,
  extensionMappingForPackage,
  extensionModuleIds,
  EXTENSION_EXTERNAL_MAPPINGS,
  EXTENSION_GLOBAL_READ_TIMING,
  ExtensionExternalContractError,
  findExtensionExternalMapping,
  formatExtensionExternalDiagnostics,
} from "@forguncy-react-workspace/core";
import type {
  DependencyDecision,
  ExtensionExternalDiagnostic,
  ExtensionExternalMapping,
  ExtensionLibraryListing,
  FrontendLibraryReference,
} from "@forguncy-react-workspace/core";

import { findDependencyDecision } from "./artifact";
import {
  collectFrontendLibraries,
  FRONTEND_LIBRARIES_FIELD_NAME,
  frontendLibraryIds,
} from "./frontend-libraries";

// ---------------------------------------------------------------------------
// The generated-module banner
// ---------------------------------------------------------------------------

/**
 * The first line of every module this file generates.
 *
 * The same reasoning #6 gives for the artifact banner: a file a machine composed has
 * to be recognizable as one, or a reviewer reading a bundle cannot tell generated
 * interposition from a dependency that happens to look like it.
 */
export const EXTENSION_EXTERNAL_GENERATED_BANNER =
  "/* generated by @forguncy-react-workspace/cell-compiler from the extension externals contract (#12) — do not edit */";

// ---------------------------------------------------------------------------
// The generated runtime error
// ---------------------------------------------------------------------------

/**
 * The one condition a generated module can report at runtime.
 *
 * One, not a table: every other code in `core`'s vocabulary is a build-time or
 * sync-time finding, and a generated module that could throw one of those would be
 * reporting a table problem from inside the page.
 */
const EXTENSION_RUNTIME_ERROR_CODE = "extension-global-missing" as const;

/**
 * The structured-error factory, generated from `core`'s rule table.
 *
 * Structured the way an Agent needs it — a stable `code`, the specifier that needed
 * the global, the library the reference names and the global itself — because a
 * message string is not branchable. The wording comes from the rule table rather
 * than from a sentence written here, so a runtime failure and the sync-time finding
 * that should have prevented it cannot drift.
 */
function renderExtensionErrorFactory(): string {
  const rule = extensionExternalDiagnosticRule(EXTENSION_RUNTIME_ERROR_CODE);
  // The rule's wording is embedded as a JSON string literal rather than pasted into
  // a hand-written literal: a remediation that later gains a quote or a newline
  // would otherwise turn the generated module into a syntax error, which is the one
  // failure mode a machine-composed file must not have.
  const ruleText = JSON.stringify(`${rule.states} ${rule.remediation}`);
  return [
    `function __fgcExtensionError(specifier, libraryId, globalName) {`,
    `  var error = new Error(`,
    `    "[extension-externals] ${EXTENSION_RUNTIME_ERROR_CODE}: " + specifier +`,
    `    " is provided by the frontend library \\"" + libraryId + "\\", which publishes the page global \\"" + globalName +`,
    `    "\\", and that global is not present. " + ${ruleText}`,
    `  );`,
    `  error.name = "ExtensionExternalError";`,
    `  error.code = ${JSON.stringify(EXTENSION_RUNTIME_ERROR_CODE)};`,
    `  error.specifier = specifier;`,
    `  error.libraryId = libraryId;`,
    `  error.globalName = globalName;`,
    `  error.fixOwner = ${JSON.stringify(rule.fixOwner)};`,
    `  return error;`,
    `}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// The interposed module
// ---------------------------------------------------------------------------

/**
 * The module the bundler loads in place of an `extension`-decided dependency.
 *
 * Three lines of substance — resolve the global, refuse without it, export it — and
 * every one of them is forced by something measured rather than chosen:
 *
 * - **The page object itself, not a wrapper and not a copy.** It is the only shape that
 *   preserves member identity across cells (`TanStackQuery.QueryClient` is one class on
 *   the page, and a wrapper would hand out a different object however faithfully it
 *   forwarded), and it is the only shape that survives a consumer's namespace import.
 *   See the next bullet for why that second point is a hard constraint and not a
 *   preference.
 * - **Resolved while this module's body runs, and failing loudly without the global.**
 *   The first version of this module was the opposite — a lazily-resolving `Proxy` that
 *   answered member access and never threw at evaluation — and it was wrong for a reason
 *   no test of the module in isolation could show. For `import * as ns from "<cjs module>"`
 *   the bundler emits `__toESM`, which enumerates `module.exports` through
 *   `Object.getOwnPropertyNames` **once**, at namespace-creation time, and builds a
 *   namespace from what it finds. A proxy whose `ownKeys` answers "nothing yet" therefore
 *   produces a namespace that can never contain the extension's members, and the authored
 *   `import { useQuery }` silently reads `undefined` for the rest of the page's life.
 *   `__esModule` does not help: in the bundler's runtime it only decides whether a
 *   `default` entry is added. Exporting the real object makes the enumeration find the
 *   real names, and a missing global becomes a named error at one moment instead of an
 *   `undefined` at every use. `core`'s `EXTENSION_EXTERNAL_INTEROP_BEHAVIOUR` holds the
 *   mechanism and the regression that pins it.
 * - **No member inventory.** #9's `verified-member-view` exists where runtime evidence
 *   produced an inventory of the host object's members; nothing comparable exists for an
 *   extension, whose surface is the vendor module's. Exporting the whole object is the
 *   honest form of "we verified the extension, not its member list".
 *
 * `moduleId` is the id the source actually imported, not the mapping's primary
 * package: a row can cover more than one package (`@tanstack/query-core` rides on the
 * `@tanstack/react-query` row), and a failure has to name the import the author
 * wrote.
 */
export function renderExtensionExternalModule(mapping: ExtensionExternalMapping, moduleId: string): string {
  if (!extensionModuleIds(mapping).includes(moduleId)) {
    throw new ExtensionExternalContractError(
      `Extension mapping "${mapping.packageName}" does not intercept "${moduleId}", so there is no module to render for it.`,
    );
  }

  const specifier = JSON.stringify(moduleId);
  const libraryId = JSON.stringify(mapping.libraryId);
  const globalName = JSON.stringify(mapping.globalName);

  return `${[
    EXTENSION_EXTERNAL_GENERATED_BANNER,
    `// ${specifier} is provided by the Forguncy frontend library ${libraryId}, which publishes`,
    `// the page global ${globalName}. The npm implementation is not in this artifact: the`,
    `// authored import is answered by the page object below, exported as it is.`,
    `//`,
    `// The global is resolved at ${EXTENSION_GLOBAL_READ_TIMING}. Reading it later would not make`,
    `// this module safer, only quieter: a consumer that imports a namespace enumerates this`,
    `// module once, when the namespace is created, so a member name that is not an own`,
    `// property at that moment never appears in the namespace at all — the authored import`,
    `// would read \`undefined\` rather than fail. #5 records that a cell's own declared`,
    `// libraries resolve before that cell's entry runs, so the global is there; if it is not,`,
    `// this module says so by name instead of leaving every use to fail on its own.`,
    `//`,
    `// No other library's global is read anywhere below, which is why this artifact cannot`,
    `// depend on one extension being loaded before another.`,
    renderExtensionErrorFactory(),
    `var __fgcExtensionValue = globalThis[${globalName}];`,
    `if (__fgcExtensionValue === undefined) {`,
    `  throw __fgcExtensionError(${specifier}, ${libraryId}, ${globalName});`,
    `}`,
    `module.exports = __fgcExtensionValue;`,
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

export interface ExtensionExternalInterception {
  /** The mapping row the interception came from. */
  readonly specifier: string;
  /** The exact module id intercepted. One interception covers one id. */
  readonly moduleId: string;
  readonly libraryId: string;
  readonly globalName: string;
  readonly mapping: ExtensionExternalMapping;
  /**
   * The source the bundler loads in place of the dependency.
   *
   * This list *is* the external mapping: `moduleId -> source` is what a resolver
   * hook or an `external`/`alias` entry is configured from, and the npm
   * implementation is absent from the artifact by construction rather than by
   * instruction (#12's "do not bundle the npm implementation into the Cell
   * artifact").
   */
  readonly source: string;
  /**
   * Whether the dependency's own implementation must be absent from the artifact.
   *
   * `true` for every row, and read off the mapping rather than inferred: the whole
   * point of an extension mapping is that the one implementation on the page is the
   * extension's, so a bundled copy alongside it is a second module identity — the
   * failure `core`'s `extension-not-declared` and #6's artifact audit each report
   * from their own side.
   */
  readonly bundledForbidden: boolean;
}

export type ExtensionExternalsActivation = "stated" | "unstated";

export interface ExtensionExternalsPlan {
  /**
   * Every module id the mapping *could* intercept, with the source generated for it.
   *
   * The table, projected. A catalog entry is a capability, not a decision: it says
   * what the compiler would generate if the artifact asked for that module through
   * an extension. Consult it to answer "what does this table know how to do".
   */
  readonly catalog: readonly ExtensionExternalInterception[];
  /**
   * The catalog entries this artifact actually activates — what a resolver hook may
   * be wired from, and only when {@link ExtensionExternalsPlan.wireable} is `true`.
   *
   * Separate from {@link catalog} for the reason #9's plan is: a row says *how* an
   * `extension` decision compiles, never that a package must be `extension`. Wiring
   * the catalog in wholesale would make the presence of a row override an `inline`
   * or `host` decision and intercept a module the artifact deliberately carries its
   * own copy of — turning a mapping table into a policy.
   *
   * Empty exactly when {@link ExtensionExternalsPlan.wireable} is `false`, which is
   * why that field is the thing a caller branches on rather than testing this array's
   * length.
   */
  readonly interceptions: readonly ExtensionExternalInterception[];
  /**
   * The `frontendLibraries` metadata for this artifact.
   *
   * Read from #6's own derivation over the same decisions rather than recomputed, so
   * the plan and the compiled artifact cannot disagree about which libraries the page
   * is told to load, and so "one `libraryId` per library, canonically ordered" keeps
   * having exactly one implementation.
   */
  readonly libraries: readonly FrontendLibraryReference[];
  /**
   * Whether the caller supplied enough input to know what this artifact activates.
   *
   * `unstated` means neither `decisions` nor `referencedSpecifiers` was given, so
   * `interceptions` is empty because the answer is unknown — not because the artifact
   * activates nothing. A caller may not wire resolver hooks from an `unstated` plan.
   *
   * An explicitly empty `decisions` or `referencedSpecifiers` is *stated*, not
   * unstated: a caller that knows there are no decisions has answered the question,
   * and reading that as "unknown" would make a known-empty artifact indistinguishable
   * from an unspecified one.
   */
  readonly activation: ExtensionExternalsActivation;
  /**
   * Whether {@link ExtensionExternalsPlan.interceptions} may be wired from at all.
   *
   * `false` for problems of two kinds, and the field is one boolean rather than a
   * conjunction a caller has to remember because the failure mode of forgetting half of
   * it is a resolver wired to something no guarantee covers:
   *
   * - `activation === "unstated"` — the caller did not say what the artifact uses, so
   *   there is nothing to wire *from*;
   * - the mapping information contradicts itself — so what is in the list cannot be
   *   trusted even though the artifact is fully specified. Two ways that happens: the
   *   table claims one module id, library or global twice, or a decision names a library
   *   or global other than the row it selects.
   *
   * The second kind needs its own statement because a diagnostic is advice. The case that
   * makes it necessary: two rows claiming one module id, where a decision naming that id
   * would otherwise satisfy the activation predicate for *both* of them and put two
   * different generated sources for one id into a wireable list. `extension-mapping-conflict`
   * is reported either way, but a caller that wires first and reports later would be
   * resolving the import by table order — the state the guard exists to prevent. A
   * contradictory mapping therefore has no wireable outcome, whatever the caller does
   * with the diagnostics.
   */
  readonly wireable: boolean;
  /**
   * Whether the caller supplied extension metadata to check the mappings against.
   *
   * A separate axis from {@link ExtensionExternalsPlan.activation}: an artifact can
   * be fully specified while its extension identities are unconfirmed, and
   * "confirmed and fine" must not look like "never checked".
   */
  readonly metadata: ExtensionExternalsActivation;
  readonly diagnostics: readonly ExtensionExternalDiagnostic[];
}

export interface PlanExtensionExternalsOptions {
  readonly mappings?: readonly ExtensionExternalMapping[];
  /**
   * The decisions the artifact is compiled against.
   *
   * Used for two things, and both need it: which mapped modules the artifact actually
   * contains, and which of them a bare `extension` claim has no row for.
   */
  readonly decisions?: readonly DependencyDecision[];
  /**
   * Specifiers the artifact references, when the caller knows them.
   *
   * The second half of "which mapped modules this cell actually uses". A bare import
   * can reach the mapping without a decision row, and a diagnostic about a module an
   * artifact never mentions is a false positive a caller then has to explain away.
   */
  readonly referencedSpecifiers?: readonly string[];
  /**
   * The extension metadata a real project reports, when the caller has it.
   *
   * The input that turns "this id came from a catalog" into "this id was confirmed
   * against a listing". Omitting it is not the same as supplying an empty listing: it
   * means the confirmation step has not happened for this build, which the plan
   * records in {@link ExtensionExternalsPlan.metadata} rather than reading as a pass.
   */
  readonly extensionLibraries?: readonly ExtensionLibraryListing[];
}

/**
 * What the compilation path does with the mapping table, plus what is wrong with it.
 *
 * Built by walking the table — and then each row's declared module ids, because that
 * is the granularity #12 writes its mapping list at. Adding a row adds one
 * interception per id it intercepts, each carrying the source generated for it; there
 * is no second list to keep in step.
 */
export function planExtensionExternals(options: PlanExtensionExternalsOptions = {}): ExtensionExternalsPlan {
  const mappings = options.mappings ?? EXTENSION_EXTERNAL_MAPPINGS;
  const decisions = options.decisions ?? [];
  const diagnostics: ExtensionExternalDiagnostic[] = [];

  // The table's own coherence first. `core`'s guard throws rather than reporting,
  // because an incoherent table is a programming error; here the throw is converted so
  // a caller doing a dry run gets a plan plus a diagnostic instead of an exception
  // that skips the rest of the audit.
  //
  // The verdict is kept, not just reported: it is what makes the plan non-wireable
  // below, so "the table is broken" cannot be downgraded to a message a caller is free
  // to read after it has already wired a resolver from the interceptions.
  let tableIsCoherent = true;
  try {
    assertExtensionExternalContract(mappings);
  } catch (error) {
    tableIsCoherent = false;
    diagnostics.push(
      createExtensionExternalDiagnostic(
        "extension-mapping-conflict",
        "extension-mapping-table",
        error instanceof ExtensionExternalContractError ? error.message : String(error),
      ),
    );
  }

  const catalog: ExtensionExternalInterception[] = [];
  for (const mapping of mappings) {
    // Rendering cannot fail here, and that is a property of the two functions rather
    // than a hope: the module id comes from the row itself, and
    // `renderExtensionExternalModule` refuses only an id the row does not intercept.
    // A change that makes rendering fallible for a row that passed the guard has to
    // come back to this loop and isolate the failure per entry, the way #9's adapter
    // case does — an exception escaping here would discard the rest of the audit.
    for (const moduleId of extensionModuleIds(mapping)) {
      catalog.push({
        specifier: mapping.packageName,
        moduleId,
        libraryId: mapping.libraryId,
        globalName: mapping.globalName,
        mapping,
        source: renderExtensionExternalModule(mapping, moduleId),
        bundledForbidden: true,
      });
    }
  }

  const libraries = collectFrontendLibraries(decisions).libraries;
  const declaredLibraryIds = new Set(frontendLibraryIds(libraries));

  // Kept, not only reported: whether a decision contradicts the row it selects decides
  // whether the interceptions below may be wired at all.
  const decisionDiagnostics = auditExtensionDecisions(decisions, mappings);
  diagnostics.push(...decisionDiagnostics);
  diagnostics.push(...auditExtensionReferences(options.referencedSpecifiers, decisions, mappings, declaredLibraryIds));

  const activation: ExtensionExternalsActivation =
    options.referencedSpecifiers === undefined && options.decisions === undefined ? "unstated" : "stated";

  // Whether the mapping information the interceptions are *derived from* is internally
  // consistent. Two ways it can fail, and both are the same problem seen from two sides:
  // the table claims one module id, library or global twice, or a decision names a
  // library or global other than the row it selects. In either state "what does this
  // import resolve to" has two answers, so a list of interceptions built from it cannot
  // be handed over as the answer — a resolver wired from it would be picking one by
  // table order.
  //
  // Keyed on the code rather than on the specific guard that produced it, because the
  // guard reports a table-level contradiction and the decision audit reports a
  // decision-level one, and the two are interchangeable as far as this question goes.
  // Every other code is deliberately absent: `extension-mapping-missing` says there is
  // no mapping, so its absence from the list is truthful, and the reference and metadata
  // findings are about the artifact's library references and the extension package,
  // while an interception is still the right thing to wire.
  const mappingInformationIsCoherent =
    tableIsCoherent && !decisionDiagnostics.some(diagnostic => diagnostic.code === "extension-mapping-conflict");

  // Decided once, so "what is wired" and "what is checked" cannot disagree about what
  // the artifact contains — the state in which a diagnostic is reported for a module
  // the plan does not intercept, or a hook is wired for one the audit never examined.
  const wireable = activation === "stated" && mappingInformationIsCoherent;
  const interceptions = wireable
    ? catalog.filter(interception => isActivated(interception, options.referencedSpecifiers, decisions, mappings))
    : [];

  // Every activated library has to be declared, and this is the check that makes #12's
  // third load-order rule enforceable rather than merely stated: an interception
  // without its reference is an import resolved against a global nothing promised to
  // load.
  for (const interception of interceptions) {
    if (declaredLibraryIds.has(interception.libraryId)) continue;
    diagnostics.push(
      createExtensionExternalDiagnostic(
        "extension-not-declared",
        interception.moduleId,
        `The artifact resolves this import through the extension library "${interception.libraryId}", but that library is not in the metadata ${FRONTEND_LIBRARIES_FIELD_NAME} is built from, so the page is never told to load it.`,
      ),
    );
  }

  let metadata: ExtensionExternalsActivation = "unstated";
  if (options.extensionLibraries !== undefined) {
    metadata = "stated";
    // Only the rows this artifact depends on, because a project is not required to have
    // installed every extension the table knows about: auditing the whole table against
    // one project's listing would report a finding for every row the artifact never
    // touches. Two sets qualify, and both are real dependencies rather than guesses —
    // the rows of the interceptions this artifact wires, and the rows of the `extension`
    // decisions it declares. The second matters even when nothing imports the package:
    // the decision still contributes a `libraryId`, so the page still has to load it or
    // render the library's own failure inside the cell.
    const usedMappings = [
      ...new Set([
        ...interceptions.map(interception => interception.mapping),
        ...decisions
          .filter(decision => decision.strategy === "extension")
          .map(decision => extensionMappingForPackage(decision.packageName, mappings))
          .filter((mapping): mapping is ExtensionExternalMapping => mapping !== undefined),
      ]),
    ];
    diagnostics.push(
      ...auditExtensionLibraryMetadata(options.extensionLibraries, { mappings: usedMappings }).map(finding =>
        createExtensionExternalDiagnostic(finding.code, finding.subject, finding.detail),
      ),
    );
  }

  return { catalog, interceptions, libraries, activation, wireable, metadata, diagnostics };
}

/**
 * Whether this artifact reaches a mapped module id.
 *
 * Called from exactly one place — the filter that produces
 * {@link ExtensionExternalsPlan.interceptions} — because the "not declared" audit
 * reads that result rather than recomputing it. Two call sites would be two chances
 * for "what is wired" and "what is checked" to disagree.
 *
 * Two routes, and they mean different things:
 *
 * - a decision naming the package, when the table intercepts it;
 * - a *reference* whose governing decision says `extension`, which is the same rule
 *   the compile boundary applies to decide what an import compiles to. A reference
 *   with no decision, or with a decision that says something else, activates nothing:
 *   nothing has said the extension provides it, so wiring a hook would override
 *   whatever the decision layer is about to say.
 *
 * The two routes match on different things, deliberately and with a bound on where
 * that difference can show: the reference route compares the *mapping object*, while
 * the decision route compares the module id. They can only disagree when one module id
 * is claimed by two rows — and in that state the table fails its own contract, which
 * makes the plan non-wireable, so the filter above never runs. Matching the mapping
 * object here as well would therefore add nothing a caller could observe; the guard
 * plus {@link ExtensionExternalsPlan.wireable} are what keep this predicate sound.
 */
function isActivated(
  interception: ExtensionExternalInterception,
  referencedSpecifiers: readonly string[] | undefined,
  decisions: readonly DependencyDecision[],
  mappings: readonly ExtensionExternalMapping[],
): boolean {
  if (
    decisions.some(
      decision => decision.strategy === "extension" && decision.packageName === interception.moduleId,
    )
  ) {
    return true;
  }

  if (referencedSpecifiers === undefined) return false;
  if (!referencedSpecifiers.includes(interception.moduleId)) return false;

  // Found the way the compile boundary finds it: a package decision governs its
  // subpath ids, so an exact comparison here would leave the very id the source
  // imports unactivated. `findDependencyDecision` is imported rather than restated
  // because it *is* that rule.
  const governing = findDependencyDecision(decisions, interception.moduleId);
  if (governing === undefined) return false;
  if (governing.strategy !== "extension") return false;
  return extensionMappingForPackage(governing.packageName, mappings) === interception.mapping;
}

/**
 * A decision list against the mapping table.
 *
 * Two questions, each a way a decision and a row can disagree:
 *
 * - an `extension` decision for a package the table cannot bind;
 * - an `extension` decision that names a library or global the row it selects does
 *   not.
 *
 * Deliberately *not* a third: an `inline`, `host` or `replace` decision for a package
 * the table maps. A row says how an `extension` decision compiles, never that the
 * package must be `extension`, so reporting one here would turn the presence of a row
 * into a policy and make a legitimate configuration unwritable — the reading #9's
 * `inline` handling was corrected to, and the reason that correction is repeated
 * rather than re-derived.
 */
function auditExtensionDecisions(
  decisions: readonly DependencyDecision[],
  mappings: readonly ExtensionExternalMapping[],
): readonly ExtensionExternalDiagnostic[] {
  const diagnostics: ExtensionExternalDiagnostic[] = [];

  for (const decision of decisions) {
    if (decision.strategy !== "extension") continue;

    const mapping = extensionMappingForPackage(decision.packageName, mappings);
    if (mapping === undefined) {
      diagnostics.push(
        createExtensionExternalDiagnostic(
          "extension-mapping-missing",
          decision.packageName,
          `The decision is \`extension\` and the mapping table does not intercept this package, so it would compile to a global nothing publishes.`,
        ),
      );
      continue;
    }

    if (decision.libraryId !== mapping.libraryId) {
      diagnostics.push(
        createExtensionExternalDiagnostic(
          "extension-mapping-conflict",
          decision.packageName,
          `The decision names the library "${decision.libraryId}" while the row for this package resolves it to "${mapping.libraryId}", so the compiled module and the reference would disagree about which library the page has to load.`,
        ),
      );
    }

    if (decision.globalName !== mapping.globalName) {
      diagnostics.push(
        createExtensionExternalDiagnostic(
          "extension-mapping-conflict",
          decision.packageName,
          `The decision names the global "${decision.globalName}" while the row for this package binds "${mapping.globalName}", so the artifact would read a global this extension never creates.`,
        ),
      );
    }
  }

  return diagnostics;
}

/**
 * A reference list against the mapping table.
 *
 * One question: a referenced module id the table intercepts, with no `extension`
 * decision behind it. That is the state #12's third load-order rule is about — the
 * artifact reads a library global, and no `libraryId` reaches `frontendLibraries`, so
 * nothing asked the page to load it. #6's own audit cannot see it either, because the
 * interposition means the import never reaches the bundler as an external one.
 *
 * A reference whose governing decision is *not* `extension` is silent: the artifact
 * carries its own copy, its own host global or its own alternative, and must not be
 * told to declare a library it deliberately does not use.
 */
function auditExtensionReferences(
  referencedSpecifiers: readonly string[] | undefined,
  decisions: readonly DependencyDecision[],
  mappings: readonly ExtensionExternalMapping[],
  declaredLibraryIds: ReadonlySet<string>,
): readonly ExtensionExternalDiagnostic[] {
  const diagnostics: ExtensionExternalDiagnostic[] = [];

  for (const specifier of referencedSpecifiers ?? []) {
    const mapping = findExtensionExternalMapping(specifier, mappings);
    if (mapping === undefined) continue;

    const governing = findDependencyDecision(decisions, specifier);
    if (governing !== undefined) continue;

    if (declaredLibraryIds.has(mapping.libraryId)) continue;

    diagnostics.push(
      createExtensionExternalDiagnostic(
        "extension-not-declared",
        specifier,
        `The mapping intercepts this import through the extension library "${mapping.libraryId}", but no decision covers it, so no reference reaches the artifact's library metadata and the page is never told to load the library.`,
      ),
    );
  }

  return diagnostics;
}

/** The module ids the plan would wire, in table order. */
export function extensionExternalModuleIds(plan: ExtensionExternalsPlan): readonly string[] {
  return plan.interceptions.map(interception => interception.moduleId);
}

/** A report block for a CI log or a PR body. */
export function formatExtensionExternalsPlan(plan: ExtensionExternalsPlan): string {
  const ids = frontendLibraryIds(plan.libraries);
  // Which of the two reasons applies is the difference between "tell me what this cell
  // uses" and "your mapping table is broken", so the report names it rather than
  // saying only that wiring was refused.
  const wiring = plan.wireable
    ? "allowed"
    : plan.activation === "unstated"
      ? "refused (no decisions and no reference list were supplied, so the answer is unknown)"
      : "refused (the mapping information contradicts itself)";
  return [
    `Extension externals catalog: ${plan.catalog.length} module id(s): ${plan.catalog.map(entry => entry.moduleId).join(", ") || "(none)"}`,
    `Activations: ${plan.activation}`,
    `Wiring: ${wiring}`,
    `Extension metadata: ${plan.metadata}${plan.metadata === "unstated" ? " (no listing supplied, so no identity was confirmed for this build)" : ""}`,
    `Active interceptions: ${plan.interceptions.map(entry => `${entry.moduleId} -> ${entry.globalName}`).join(", ") || "(none)"}`,
    `${FRONTEND_LIBRARIES_FIELD_NAME}: ${ids.join(", ") || "(none)"}`,
    plan.diagnostics.length === 0
      ? "No extension externals diagnostics."
      : `${plan.diagnostics.length} extension externals diagnostic(s):\n${formatExtensionExternalDiagnostics(plan.diagnostics)}`,
  ].join("\n");
}

/**
 * Every module id the mapping table intercepts.
 *
 * Takes the mapping list so a caller comparing a bundle against the table is
 * comparing against the same table it planned from, rather than against the shipped
 * default.
 */
export function interceptedExtensionExternalModuleIds(
  mappings: readonly ExtensionExternalMapping[] = EXTENSION_EXTERNAL_MAPPINGS,
): readonly string[] {
  return extensionInterceptedModuleIds(mappings);
}
