/**
 * The compilation projection of #9's host module bridge.
 *
 * Decision source: GitHub Issue #9 — "Spec: host module bridge for React,
 * ReactDOM, antd and built-in globals"
 * (https://github.com/Mang-X/forguncy-react-workspace/issues/9), which is itself
 * downstream of:
 * - #4 "application ownership boundaries and dependency strategy semantics"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/4
 * - #5 "establish the ReactCellType target/runtime contract on Forguncy 12.0.100"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/5
 * - #6 "generated ReactCellType artifact and compiler boundary"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/6
 *
 * `core` owns *which* import is bound to which host identity and *why*. This
 * module owns what the compilation path does with that: the source handed to the
 * bundler in place of a dependency, the guard emitted once per artifact, and the
 * diagnostics the bridge reports about a decision list.
 *
 * Three things here are deliberate, and each is the answer to one of #9's
 * acceptance criteria:
 *
 * 1. **The interception is keyed on the specifier and the generated module is a
 *    pure function of the mapping.** No function in this module takes authored
 *    source as an argument, so there is no code path that could rewrite one (#9:
 *    "Standard source imports remain unchanged") and no place for a
 *    package-specific AST rule to live (#9: "without hardcoding package-specific
 *    AST rewrites"). {@link planHostBridge} derives its interception set by
 *    walking the mapping table, so a new row is the whole of the change.
 * 2. **A required global fails through a structured error, not through
 *    `undefined`.** #5 records `React` and `ReactDOM` as `always` available, so
 *    their absence means the artifact is running somewhere that is not the pinned
 *    target — a state worth failing on with a code an Agent can branch on, rather
 *    than one whose symptom appears wherever the value is first used.
 * 3. **A preset-conditional global does not throw.** #5 measured two cells on one
 *    page disagreeing about the same preset global, so absence is a supported
 *    state. It is reported at build time, when the cell's own preset is known, and
 *    at runtime it stays `undefined` exactly as #5 says it will be.
 *
 * Scope note: this module generates the interposed modules and the guard, and
 * audits a decision list against the table. It does not drive a bundler, assemble
 * an artifact, or emit a diagnostic into #6's artifact report — wiring the bridge
 * into the compile boundary is the compiler MVP's job (#7), and asserting a
 * bridge diagnostic through `CellArtifactDiagnostic` would put two vocabularies in
 * one report before anyone has decided how they compose.
 */

import {
  assertHostBridgeContract,
  CELL_PRESET_LIBRARIES,
  findHostBridgeModuleMapping,
  hostBridgeAdapterMappings,
  hostBridgeBindingFor,
  hostBridgeGlobalIsAlwaysAvailable,
  hostBridgeGlobalMappings,
  hostBridgeInterceptedModuleIds,
  hostBridgeModuleIds,
  hostBridgeShapeFor,
  HOST_BRIDGE_DIAGNOSTIC_RULES,
  HOST_BRIDGE_MAPPINGS,
  HostBridgeContractError,
} from "@forguncy-react-workspace/core";
import type {
  CellPresetLibrary,
  DependencyDecision,
  HostBridgeAdapterMapping,
  HostBridgeDiagnosticCode,
  HostBridgeGlobalMapping,
  HostBridgeMapping,
  HostBridgeMappingKind,
  HostBridgeModuleShape,
  JSX_RUNTIME_ADAPTER_EXPORTS,
} from "@forguncy-react-workspace/core";

import { findDependencyDecision } from "./artifact";

// ---------------------------------------------------------------------------
// The generated-module banner
// ---------------------------------------------------------------------------

/**
 * The first line of every module this file generates.
 *
 * The same reasoning #6 gives for the artifact banner: a file a machine composed
 * has to be recognizable as one, or a reviewer reading a bundle cannot tell
 * generated interposition from a dependency that happens to look like it.
 */
export const HOST_BRIDGE_GENERATED_BANNER =
  "/* generated by @forguncy-react-workspace/cell-compiler from the host bridge contract (#9) — do not edit */";

// ---------------------------------------------------------------------------
// Generated runtime error
// ---------------------------------------------------------------------------

/**
 * The three conditions a generated module can report at runtime.
 *
 * Only these: `host-mapping-missing`, `host-module-duplicated`,
 * `host-adapter-not-used` and `host-mapping-conflict` are build-time findings, and a
 * generated module that could throw one of those would be reporting a table problem
 * from inside the page.
 */
const RUNTIME_ERROR_FUNCTIONS = {
  "host-global-missing": "__fgcHostBridgeErrorMissing",
  "host-global-incompatible": "__fgcHostBridgeErrorIncompatible",
  "host-member-not-verified": "__fgcHostBridgeErrorUnverified",
} as const satisfies Partial<Record<HostBridgeDiagnosticCode, string>>;

type RuntimeErrorCode = keyof typeof RUNTIME_ERROR_FUNCTIONS;

/**
 * One structured-error factory, generated from `core`'s rule table.
 *
 * Structured the way an Agent needs it — a stable `code`, the specifier that needed
 * the global, the global's name, and the member when the global exists but the member
 * is the problem — because #9's third acceptance criterion is a *useful* diagnostic
 * and a message string is not branchable.
 *
 * The message's wording comes from the rule table rather than from a sentence written
 * here, so a runtime failure and its build-time counterpart cannot drift. Emitted
 * per code rather than as one always-on dispatcher so a module that can only fail one
 * way does not carry the strings for the other two — #21 measures this budget.
 */
function renderErrorFactory(code: RuntimeErrorCode): string {
  const rule = HOST_BRIDGE_DIAGNOSTIC_RULES[code];
  const name = RUNTIME_ERROR_FUNCTIONS[code];
  return [
    `function ${name}(specifier, globalName, member) {`,
    `  var target = member === undefined ? globalName : globalName + "." + member;`,
    `  var error = new Error("[host-bridge] ${code}: " + specifier + " is bridged to " + target + ". ${rule.states} ${rule.remediation}");`,
    `  error.name = "HostBridgeError";`,
    `  error.code = ${JSON.stringify(code)};`,
    `  error.specifier = specifier;`,
    `  error.globalName = globalName;`,
    `  error.member = member === undefined ? null : member;`,
    `  error.fixOwner = ${JSON.stringify(rule.fixOwner)};`,
    `  return error;`,
    `}`,
  ].join("\n");
}

/** The factories a generated unit needs, in the order they are declared. */
function renderErrorFactories(codes: readonly RuntimeErrorCode[]): string {
  return codes.map(renderErrorFactory).join("\n");
}

// ---------------------------------------------------------------------------
// Host-global modules
// ---------------------------------------------------------------------------

/**
 * The module the bundler loads in place of a `host`-decided dependency.
 *
 * Keyed on the module id, not only on the mapping, because a row can promise two
 * different things: `react-dom`'s row binds the package id to the host object and
 * narrows its subpath. Rendering from the mapping alone would make
 * `react-dom/client` an alias for the whole `ReactDOM` object, which is the
 * failure this signature exists to make impossible.
 *
 * Three shapes, each chosen by data rather than by a decision here:
 *
 * - **`host-identity`** — the module *is* the page object. The exported value is
 *   the global itself, never a wrapper: an interposed module that re-exported
 *   through a proxy would satisfy every functional test and still fail the identity
 *   check that matters, since two cells comparing their React objects would no
 *   longer see the same one. Two refusal behaviours inside this shape, both from
 *   #5's availability record:
 *   - `always` (React, ReactDOM) is checked and refuses without the global, because
 *     its absence means the artifact is not on the target it was compiled for — the
 *     later alternative is a `TypeError` naming whichever property the cell happened
 *     to touch first;
 *   - `after-the-declared-preset-resolves` (`antd`) is bound as-is, because #5
 *     measured a legal cell in which the same global is absent, so a throw here
 *     would make a legal cell illegal.
 * - **`verified-member-view`** — the module is a view over the page object that
 *   forwards exactly the members #5 observed and refuses every other name. Used
 *   where #9 makes a *surface* claim rather than an identity claim
 *   (`react-dom/client`), never where it makes an identity claim.
 */
export function renderHostBridgeGlobalModule(mapping: HostBridgeGlobalMapping, moduleId: string): string {
  const shape = hostBridgeShapeFor(mapping, moduleId);
  if (shape === undefined) {
    throw new HostBridgeContractError(
      `Host bridge mapping "${mapping.specifier}" does not intercept "${moduleId}", so there is no module to render for it.`,
    );
  }

  if (shape === "verified-member-view") {
    return renderHostBridgeVerifiedMemberView(mapping, moduleId);
  }

  const lines = [HOST_BRIDGE_GENERATED_BANNER];

  if (hostBridgeGlobalIsAlwaysAvailable(mapping)) {
    lines.push(
      renderErrorFactories(["host-global-missing"]),
      `var __fgcHostBridgeValue = globalThis[${JSON.stringify(mapping.globalName)}];`,
      `if (__fgcHostBridgeValue === undefined) {`,
      `  throw __fgcHostBridgeErrorMissing(${JSON.stringify(moduleId)}, ${JSON.stringify(mapping.globalName)}, undefined);`,
      `}`,
      `module.exports = __fgcHostBridgeValue;`,
    );
  } else {
    lines.push(
      `// #5 records this global as available only once the cell's declared preset has`,
      `// resolved, and as absent otherwise, so an absent value is a supported state.`,
      `module.exports = globalThis[${JSON.stringify(mapping.globalName)}];`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/**
 * The narrowed view a subpath gets when #9 promises a surface rather than an object.
 *
 * `verifiedMembers` is the load-bearing input: the view forwards exactly the
 * members the row recorded as observed and refuses every other name with
 * `host-member-not-verified`. Refusing rather than forwarding matters because the
 * two available alternatives are both wrong in the same quiet way — the host object
 * may simply not carry an unobserved member (so the import becomes `undefined` and
 * fails wherever it is called), or it may carry something nobody has verified (so
 * the cell silently depends on an unmeasured surface).
 *
 * A `Proxy` rather than a plain object, because a plain object *is* the `undefined`
 * answer: `client.hydrateRoot` would be `undefined` with no explanation. The trap
 * is deliberately narrow in the other direction too — the names a CommonJS consumer
 * asks a module for before it asks for any real member (`__esModule`, `default`,
 * `then`) are answered without consulting the host object, because otherwise a
 * bundler's interop helper would trip the refusal before the cell's own code ran.
 */
function renderHostBridgeVerifiedMemberView(mapping: HostBridgeGlobalMapping, moduleId: string): string {
  const binding = hostBridgeBindingFor(mapping, moduleId);
  if (binding?.members === undefined) {
    throw new HostBridgeContractError(
      `Host bridge mapping "${mapping.specifier}" declares no verified-member surface for "${moduleId}".`,
    );
  }

  const members = JSON.stringify([...binding.members]);
  const specifier = JSON.stringify(moduleId);
  const globalName = JSON.stringify(mapping.globalName);

  return `${[
    HOST_BRIDGE_GENERATED_BANNER,
    `// A view over the host object, not the host object: #9 promises the surface that`,
    `// runtime evidence established for this module id, so a member outside it is`,
    `// refused rather than forwarded or resolved to \`undefined\`.`,
    renderErrorFactories(["host-global-missing", "host-global-incompatible", "host-member-not-verified"]),
    `var __fgcHostBridgeHost = globalThis[${globalName}];`,
    `if (__fgcHostBridgeHost === undefined) {`,
    `  throw __fgcHostBridgeErrorMissing(${specifier}, ${globalName}, undefined);`,
    `}`,
    ``,
    `// The members #5 observed on the host object, in declaration order.`,
    `var __fgcHostBridgeMembers = ${members};`,
    `var __fgcHostBridgeTarget = {};`,
    `for (var __fgcHostBridgeIndex = 0; __fgcHostBridgeIndex < __fgcHostBridgeMembers.length; __fgcHostBridgeIndex++) {`,
    `  (function (member) {`,
    `    Object.defineProperty(__fgcHostBridgeTarget, member, {`,
    `      enumerable: true,`,
    `      configurable: true,`,
    `      get: function () {`,
    `        var value = __fgcHostBridgeHost[member];`,
    `        if (value === undefined) {`,
    `          throw __fgcHostBridgeErrorIncompatible(${specifier}, ${globalName}, member);`,
    `        }`,
    `        return value;`,
    `      },`,
    `    });`,
    `  })(__fgcHostBridgeMembers[__fgcHostBridgeIndex]);`,
    `}`,
    ``,
    `// The default export answers with this guarded view rather than the raw target, so`,
    `// the interop protocol is not a way to reach the underlying object without the trap.`,
    `var __fgcHostBridgeView = new Proxy(__fgcHostBridgeTarget, {`,
    `  get: function (target, property) {`,
    `    if (typeof property !== "string") return undefined;`,
    `    if (Object.prototype.hasOwnProperty.call(target, property)) return target[property];`,
    `    // Interop protocol names a CommonJS consumer asks for before any real member.`,
    `    // Answered without consulting the host object, so a loader's helper cannot`,
    `    // trip the refusal below before the cell's own code runs.`,
    `    if (property === "__esModule" || property === "then") return undefined;`,
    `    if (property === "default") return __fgcHostBridgeView;`,
    `    throw __fgcHostBridgeErrorUnverified(${specifier}, ${globalName}, property);`,
    `  },`,
    `  has: function (target, property) {`,
    `    return Object.prototype.hasOwnProperty.call(target, property);`,
    `  },`,
    `});`,
    `module.exports = __fgcHostBridgeView;`,
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// JSX runtime adapter
// ---------------------------------------------------------------------------

/**
 * The generated JSX runtime adapter.
 *
 * The two-parameter/two-case rule below is the one
 * `MangMax/forguncy-react-library` verified and its regression test exists to keep:
 * `jsx(type, props, key)` and `createElement(type, config, children)` disagree
 * about the third parameter, so the key is never forwarded as the third argument
 * and no third argument is passed when there is no key. `core`'s
 * `JSX_RUNTIME_ADAPTER_RULES` is the contract this code implements; the comments
 * here are the *why* for a reader who has the generated file and not the Spec.
 *
 * Two additions to the verified form, both from #9 rather than from taste:
 *
 * - the host lookup is **lazy**, so evaluating the module while `globalThis.React`
 *   is absent does not throw (`evaluation-must-not-throw`) while a call that
 *   actually needs React fails with the bridge's structured error;
 * - `Fragment` is exposed through a **getter**, because it is a *guarded* member —
 *   #5 never read `React.Fragment` off the host object, so the bridge checks it on
 *   access instead of binding a possibly-undefined snapshot at module load.
 *
 * `jsxs` and `jsxDEV` share the implementation. The dev-only arguments are accepted
 * and ignored: they carry debugging metadata, and reproducing it would mean
 * reimplementing a React-internal surface.
 *
 * `moduleId` is the id the source actually imported. Both runtime ids share this
 * adapter, so it is what makes a failure from a dev build name
 * `react/jsx-dev-runtime` rather than the row's first id.
 */
export function renderHostBridgeAdapterModule(mapping: HostBridgeAdapterMapping, moduleId: string): string {
  // The adapter id decides which host member is the delegate. `jsx-runtime` means the
  // host React object's `createElement` — a second adapter id would need its own
  // delegate here, which is why the delegate is not a mapping field: a mapping says
  // which members are *required*, and the adapter knows what to do with them.
  const globalName = "React";
  const createElement = mapping.requiredHostMembers.includes("createElement") ? "createElement" : undefined;

  if (!hostBridgeModuleIds(mapping).includes(moduleId)) {
    throw new HostBridgeContractError(
      `Host bridge adapter "${mapping.specifier}" does not intercept "${moduleId}", so there is no module to render for it.`,
    );
  }

  if (createElement === undefined) {
    throw new HostBridgeContractError(
      `Host bridge adapter "${mapping.specifier}" declares no "createElement" among its required host members, so the generated adapter would have nothing to delegate to.`,
    );
  }

  const fragmentGuarded = (mapping.guardedMembers ?? []).includes("Fragment");

  const lines = [
    HOST_BRIDGE_GENERATED_BANNER,
    renderErrorFactories(["host-global-missing", "host-global-incompatible"]),
    ``,
    `function __fgcHostBridgeReact() {`,
    `  var value = globalThis[${JSON.stringify(globalName)}];`,
    `  if (value === undefined) {`,
    `    throw __fgcHostBridgeErrorMissing(${JSON.stringify(moduleId)}, ${JSON.stringify(globalName)}, undefined);`,
    `  }`,
    `  return value;`,
    `}`,
    ``,
    `// jsx(type, props, key) — the third parameter is the key, NOT children, and`,
    `// createElement's third parameter IS children. Passing the key through as the`,
    `// third argument sets children to the key and drops the key.`,
    `function __fgcHostBridgeJsx(type, props, key) {`,
    `  var React = __fgcHostBridgeReact();`,
    `  if (key === undefined) {`,
    `    // Exactly two arguments: an explicit undefined third one would take`,
    `    // createElement's children branch and overwrite props.children.`,
    `    return React.${createElement}(type, props);`,
    `  }`,
    `  return React.${createElement}(type, Object.assign({}, props, { key: key }));`,
    `}`,
    ``,
    `module.exports = {`,
    `  jsx: __fgcHostBridgeJsx,`,
    `  jsxs: __fgcHostBridgeJsx,`,
    `  jsxDEV: __fgcHostBridgeJsx,`,
    `};`,
  ];

  if (fragmentGuarded) {
    lines.push(
      ``,
      `// Fragment is a guarded member: #5 did not observe it on the host object, so it`,
      `// is checked on access rather than bound as a snapshot at module load.`,
      `Object.defineProperty(module.exports, "Fragment", {`,
      `  enumerable: true,`,
      `  get: function () {`,
      `    var React = __fgcHostBridgeReact();`,
      `    if (React.Fragment === undefined) {`,
      `      throw __fgcHostBridgeErrorIncompatible(${JSON.stringify(moduleId)}, ${JSON.stringify(globalName)}, "Fragment");`,
      `    }`,
      `    return React.Fragment;`,
      `  },`,
      `});`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/**
 * The interposed module for a mapping, whichever kind it is.
 *
 * Dispatch is on `kind`, which is the mapping's declaration of whether a page
 * object has the module's shape. Nothing inspects the specifier to decide.
 */
/**
 * The interposed module for one intercepted module id.
 *
 * Dispatch is on the module id's declared shape, which is the mapping's own
 * statement of whether the import is the host object, a view over it, or generated
 * code. Nothing inspects the specifier to decide, and a module id the table does not
 * intercept is refused rather than rendered.
 */
export function renderHostBridgeModule(mapping: HostBridgeMapping, moduleId: string): string {
  if (mapping.kind === "jsx-runtime-adapter") {
    return renderHostBridgeAdapterModule(mapping, moduleId);
  }
  return renderHostBridgeGlobalModule(mapping, moduleId);
}

// ---------------------------------------------------------------------------
// The artifact guard
// ---------------------------------------------------------------------------

export interface RenderHostBridgeGuardOptions {
  readonly mappings?: readonly HostBridgeMapping[];
  /**
   * The host React version recorded in the lock this build is verified against.
   *
   * Supplying it emits the identity check; omitting it means no identity check was
   * performed for this build, which is a weaker validation and is the reason this
   * is a required field rather than an optional one — a caller has to say which of
   * the two it is doing.
   */
  readonly recordedHostReactVersion: string | undefined;
  /** The specifiers the artifact actually references, when known. */
  readonly referencedSpecifiers?: readonly string[];
}

/**
 * The guard emitted once per artifact, at cell entry.
 *
 * Why a guard *and* per-module checks: the module checks fire at whatever moment
 * the bundler evaluates the interposed module, which is a bundler decision, while
 * the guard fires where the cell begins. For the always-available globals that is
 * the difference between failing before a cell's first statement and failing
 * somewhere inside a generated module.
 *
 * What the guard deliberately does **not** do: report preset-conditional globals.
 * #5 records their absence as a supported per-cell state, so a guard that threw
 * would take a legal cell and break it. Those are build-time diagnostics, where
 * the cell's declared preset is known.
 *
 * `recordedHostReactVersion` is compared as an exact string. #5 measured the host
 * as `React.version === "19.2.7"`, so equality is what the evidence supports; a
 * semver-range comparison here would be a policy nobody has decided yet (#16's
 * territory).
 */
export function renderHostBridgeGuard(options: RenderHostBridgeGuardOptions): string {
  const mappings = options.mappings ?? HOST_BRIDGE_MAPPINGS;
  const referenced =
    options.referencedSpecifiers === undefined ? undefined : new Set(options.referencedSpecifiers);
  const isReferenced = (mapping: HostBridgeMapping): boolean =>
    referenced === undefined || hostBridgeModuleIds(mapping).some(id => referenced.has(id));

  const alwaysAvailable = hostBridgeGlobalMappings(mappings)
    .filter(mapping => hostBridgeGlobalIsAlwaysAvailable(mapping))
    .filter(isReferenced);

  const lines = [
    HOST_BRIDGE_GENERATED_BANNER,
    `// Emitted once per artifact, at cell entry. Required globals fail here; globals`,
    `// whose absence #5 records as a supported state are reported at build time.`,
    renderErrorFactories(["host-global-missing", "host-global-incompatible"]),
    `(function __fgcHostBridgeGuard() {`,
  ];

  for (const mapping of alwaysAvailable) {
    const globalName = JSON.stringify(mapping.globalName);
    const specifier = JSON.stringify(mapping.specifier);
    lines.push(
      `  var __fgc${sanitizeBindingName(mapping.specifier)} = globalThis[${globalName}];`,
      `  if (__fgc${sanitizeBindingName(mapping.specifier)} === undefined) {`,
      `    throw __fgcHostBridgeErrorMissing(${specifier}, ${globalName}, undefined);`,
      `  }`,
    );

    if (mapping.identityField === "hostReactVersion" && options.recordedHostReactVersion !== undefined) {
      lines.push(
        `  // The lock's recorded host identity, checked because #5 verified`,
        `  // \`React.version\` on the injected object and this mapping names`,
        `  // \`hostReactVersion\` as its identity field.`,
        `  if (__fgc${sanitizeBindingName(mapping.specifier)}.version !== ${JSON.stringify(options.recordedHostReactVersion)}) {`,
        `    throw __fgcHostBridgeErrorIncompatible(${specifier}, ${globalName}, "version");`,
        `  }`,
      );
    }
  }

  lines.push(`})();`);
  return `${lines.join("\n")}\n`;
}

/**
 * A specifier turned into something usable inside an identifier.
 *
 * Generated code has to name its locals, and a local named after `react-dom/client`
 * would not parse. Deterministic rather than random so two builds of one plan
 * produce identical source.
 */
function sanitizeBindingName(specifier: string): string {
  return specifier
    .split(/[^0-9A-Za-z]+/)
    .filter(segment => segment.length > 0)
    .map(segment => `${segment[0]?.toUpperCase() ?? ""}${segment.slice(1)}`)
    .join("");
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

/**
 * One bridge finding.
 *
 * `detail` carries the offending value and `code` comes from `core`'s shared
 * vocabulary, so the same code can be reported at build time and thrown at
 * runtime. `member` is separate from `detail` because it is the one part of a
 * message a caller may want to branch on without parsing.
 */
export interface HostBridgeDiagnostic {
  readonly code: HostBridgeDiagnosticCode;
  readonly specifier: string;
  readonly detail: string;
  readonly member?: string;
}

export function createHostBridgeDiagnostic(
  code: HostBridgeDiagnosticCode,
  specifier: string,
  detail: string,
  member?: string,
): HostBridgeDiagnostic {
  return { code, specifier, detail, ...(member === undefined ? {} : { member }) };
}

/** The rule behind a diagnostic, so a report can print guidance without the code. */
export function hostBridgeDiagnosticRule(code: HostBridgeDiagnosticCode) {
  return HOST_BRIDGE_DIAGNOSTIC_RULES[code];
}

/** One line per diagnostic, including what to do about it. */
export function formatHostBridgeDiagnostic(diagnostic: HostBridgeDiagnostic): string {
  const rule = HOST_BRIDGE_DIAGNOSTIC_RULES[diagnostic.code];
  return `${diagnostic.specifier}: [${diagnostic.code}] ${rule.label} — ${diagnostic.detail} (fix owner: ${rule.fixOwner})`;
}

export function formatHostBridgeDiagnostics(diagnostics: readonly HostBridgeDiagnostic[]): string {
  return diagnostics.map(formatHostBridgeDiagnostic).join("\n");
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

export interface HostBridgeInterception {
  /** The mapping row the interception came from. */
  readonly specifier: string;
  /** The exact module id intercepted. One interception covers one id. */
  readonly moduleId: string;
  readonly kind: HostBridgeMappingKind;
  /**
   * What the interposed module promises for this id.
   *
   * A row can promise different things per id — `react-dom` binds the host object,
   * its subpath gets a narrowed view — so this is the shape the source was generated
   * for, and it is what a reviewer checks against #9's mapping bullets.
   */
  readonly shape: HostBridgeModuleShape;
  readonly mapping: HostBridgeMapping;
  /** The source the bundler loads in place of the dependency. */
  readonly source: string;
  /**
   * Whether the dependency's own implementation must be absent from the artifact.
   *
   * Read off the mapping rather than off the decision, because the reason differs
   * by kind and both reasons are about the mapping: a `host-global` row means the
   * page already has this module, so a bundled copy is a second implementation of
   * something that exists; an adapter row means the *published* module would carry
   * its own React, which is the duplicate the adapter exists to avoid. Either way
   * the flag is the answer to #9's first acceptance criterion at the planning
   * level.
   */
  readonly bundledForbidden: boolean;
}

export interface HostBridgePlan {
  /**
   * Every module id the bridge *could* intercept, with the source for its shape.
   *
   * The table, projected. A catalog entry is a capability, not a decision: it says
   * what the bridge would generate if the artifact asked for that module through
   * the host. Consult it to answer "what does the bridge know how to do".
   */
  readonly catalog: readonly HostBridgeInterception[];
  /**
   * The catalog entries this artifact actually activates — what a resolver hook may
   * be wired from.
   *
   * Separate from {@link catalog} because a mapping says *how* a `host` decision
   * compiles, never that a package must be `host`. Wiring the catalog in wholesale
   * would make the presence of a row override an `inline`/`extension`/`replace`
   * decision and intercept a module the artifact deliberately carries its own copy
   * of, which is the policy this contract exists to avoid.
   */
  readonly interceptions: readonly HostBridgeInterception[];
  /**
   * Whether the caller supplied enough input to know what this artifact activates.
   *
   * `unstated` means neither `decisions` nor `referencedSpecifiers` was given, so
   * `interceptions` is empty because the answer is unknown — not because the
   * artifact activates nothing. A caller may not wire resolver hooks from an
   * `unstated` plan.
   */
  readonly activation: HostBridgeActivation;
  readonly diagnostics: readonly HostBridgeDiagnostic[];
}

export type HostBridgeActivation = "stated" | "unstated";

export interface PlanHostBridgeOptions {
  readonly mappings?: readonly HostBridgeMapping[];
  /**
   * The decisions the artifact is compiled against.
   *
   * Used for two things, and both need it: which bridged modules the artifact
   * actually contains, and which of them a bare `host` claim has no mapping for.
   */
  readonly decisions?: readonly DependencyDecision[];
  /**
   * Specifiers the artifact references, when the caller knows them.
   *
   * The second half of "which bridged modules this cell actually uses". A bare
   * import can reach the bridge without a decision row, and a diagnostic about a
   * module an artifact never mentions is a false positive a caller then has to
   * explain away.
   */
  readonly referencedSpecifiers?: readonly string[];
  /**
   * The preset the cell declares, when known.
   *
   * The input that turns a preset-conditional mapping's absence into a *build*
   * diagnostic instead of a runtime surprise — for the imports the cell actually
   * uses. Omitting it is not the same as declaring `None`: it means the caller did
   * not tell the bridge what the cell declares, and the bridge then reports nothing
   * rather than guessing.
   */
  readonly cellPreset?: CellPresetLibrary["name"];
}

/**
 * What the compilation path does with the bridge, plus what is wrong with it.
 *
 * Built by walking the mapping table — and then each row's declared module ids,
 * because that is the granularity #9 writes its mapping list at. Adding a row adds
 * one interception per id it intercepts, each carrying the source generated for its
 * own shape; there is no second list to keep in step.
 */
export function planHostBridge(options: PlanHostBridgeOptions = {}): HostBridgePlan {
  const mappings = options.mappings ?? HOST_BRIDGE_MAPPINGS;
  const diagnostics: HostBridgeDiagnostic[] = [];

  // The table's own coherence first. `core`'s guard throws rather than reporting,
  // because an incoherent table is a programming error; here the throw is
  // converted so a caller doing a dry run gets a plan plus a diagnostic instead of
  // an exception that skips the rest of the audit.
  try {
    assertHostBridgeContract(mappings);
  } catch (error) {
    diagnostics.push(
      createHostBridgeDiagnostic(
        "host-mapping-conflict",
        "bridge-mapping-table",
        error instanceof HostBridgeContractError ? error.message : String(error),
      ),
    );
  }

  const catalog: HostBridgeInterception[] = [];
  for (const mapping of mappings) {
    for (const moduleId of hostBridgeModuleIds(mapping)) {
      const shape = hostBridgeShapeFor(mapping, moduleId);
      if (shape === undefined) continue;

      // Rendering is the other half of "a dry run returns a plan, not an exception".
      // The contract guard above catches a malformed row, but some malformed rows are
      // also unrenderable — an adapter with no delegate throws while generating, not
      // while validating — so a failure here is a diagnostic and a skipped entry
      // rather than an exception that discards the rest of the audit.
      let source: string;
      try {
        source = renderHostBridgeModule(mapping, moduleId);
      } catch (error) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-conflict",
            moduleId,
            `The mapping for this module id cannot be rendered: ${error instanceof Error ? error.message : String(error)}`,
          ),
        );
        continue;
      }

      catalog.push({
        specifier: mapping.specifier,
        moduleId,
        kind: mapping.kind,
        shape,
        mapping,
        source,
        bundledForbidden: true,
      });
    }
  }

  // A duplicated claim would make the plan's interception order decide the result,
  // which is the same failure `host-mapping-conflict` reports for the table; the
  // guard above already covers it, and this keeps the check meaningful when a
  // caller passes a table it built itself.
  const seen = new Map<string, string>();
  for (const interception of catalog) {
    const owner = seen.get(interception.moduleId);
    if (owner !== undefined && owner !== interception.specifier) {
      diagnostics.push(
        createHostBridgeDiagnostic(
          "host-mapping-conflict",
          interception.moduleId,
          `Both "${owner}" and "${interception.specifier}" intercept this module id, so which source is used would depend on table order.`,
        ),
      );
    }
    seen.set(interception.moduleId, interception.specifier);
  }

  const decisions = options.decisions ?? [];
  const usage = hostBridgeUsage(decisions, options.referencedSpecifiers, mappings);
  const interceptions = catalog.filter(interception => usage.activated.has(interception.moduleId));

  diagnostics.push(...auditHostBridgeDecisions(decisions, mappings));
  diagnostics.push(...auditHostBridgePresetReadiness(mappings, options.cellPreset, usage));

  return { catalog, interceptions, activation: usage.state, diagnostics };
}

export interface HostBridgeUsage {
  readonly state: HostBridgeActivation;
  /**
   * The module ids the bridge is asked to intercept, and the only ones a resolver
   * hook may be wired from.
   */
  readonly activated: ReadonlySet<string>;
  /**
   * The module ids whose *host global* the artifact relies on.
   *
   * A superset of {@link activated}, and not the same question — conflating the two
   * is what made the first version of the preset audit wrong in both directions:
   *
   * - a `host` decision activates the bridge *and* depends on the page providing the
   *   global;
   * - a reference to a gated module with **no** decision does not activate anything
   *   (nothing has said the page provides it, so a hook would be overriding an
   *   unresolved import) but it *is* a real preset question, because the artifact uses
   *   the import either way;
   * - a reference **overridden** by a non-`host` decision depends on nothing: the
   *   artifact carries its own copy, its own extension global, or its own alternative,
   *   and must not be told to declare a preset it deliberately does not use.
   */
  readonly presetDependent: ReadonlySet<string>;
}

/**
 * What this artifact asks of the bridge, and of the host's preset chains.
 *
 * `unstated` when neither input was supplied: the answer is unknown, and the caller is
 * told so rather than handed an empty activation that reads like a decision.
 *
 * Takes the mapping table for the same reason the catalog does. A project-supplied row
 * has to participate in activation and in the preset audit, not merely appear in the
 * catalog — a caller that extends the table and then finds its row invisible to every
 * reference would be looking at a capability the bridge refuses to use.
 */
function hostBridgeUsage(
  decisions: readonly DependencyDecision[],
  referencedSpecifiers: readonly string[] | undefined,
  mappings: readonly HostBridgeMapping[],
): HostBridgeUsage {
  if (referencedSpecifiers === undefined && decisions.length === 0) {
    return { state: "unstated", activated: new Set(), presetDependent: new Set() };
  }

  const adapterModuleIds = new Set(hostBridgeAdapterMappings(mappings).flatMap(hostBridgeModuleIds));
  const activated = new Set<string>();
  const presetDependent = new Set<string>();

  for (const decision of decisions) {
    // A JSX runtime id is not a `host` strategy — the resolver requires `replace`
    // for it, because the published module would carry its own React — so the adapter
    // is activated by the id being reached, and a decision naming one is what a
    // compiler would otherwise act on.
    if (decision.strategy === "host") {
      activated.add(decision.packageName);
      presetDependent.add(decision.packageName);
    } else if (adapterModuleIds.has(decision.packageName)) {
      activated.add(decision.packageName);
    }
  }

  for (const specifier of referencedSpecifiers ?? []) {
    if (adapterModuleIds.has(specifier)) {
      activated.add(specifier);
      continue;
    }

    if (findHostBridgeModuleMapping(specifier, mappings) === undefined) continue;

    // The governing decision is found the way the compile boundary finds it: a
    // `react-dom` decision governs an import of `react-dom/client`. Using an exact
    // comparison here would leave the very module id the source imports
    // unactivated — the subpath would be in the catalog and never wired.
    const governing = findDependencyDecision(decisions, specifier);

    if (governing === undefined) {
      // A reference alone never activates a host-global mapping: without a `host`
      // decision nothing says the page provides the module, and wiring a hook would
      // override whatever the decision layer is going to say about it. It is still a
      // real preset question, because the artifact imports it either way.
      presetDependent.add(specifier);
      continue;
    }

    if (governing.strategy === "host") {
      activated.add(specifier);
      presetDependent.add(specifier);
    }
    // Any other governing strategy carries its own copy, its own global, or its own
    // alternative: neither activated nor dependent on a host global.
  }

  return { state: "stated", activated, presetDependent };
}

/**
 * A decision list against the mapping table.
 *
 * Three questions, each a way a decision and a mapping can disagree:
 *
 * - a `host` decision for a module the table cannot bind;
 * - a JSX runtime id resolved by a page global, when only the adapter has the
 *   module's shape;
 * - a bridged module that the decision bundles anyway, which is the duplicated
 *   identity #9's first acceptance criterion is about.
 */
function auditHostBridgeDecisions(
  decisions: readonly DependencyDecision[],
  mappings: readonly HostBridgeMapping[],
): readonly HostBridgeDiagnostic[] {
  const diagnostics: HostBridgeDiagnostic[] = [];
  const adapterModuleIds = new Set(hostBridgeAdapterMappings(mappings).flatMap(hostBridgeModuleIds));

  for (const decision of decisions) {
    const packageName = decision.packageName;
    const mapping = findHostBridgeModuleMapping(packageName, mappings);
    const providesModule = decision.strategy === "host" || decision.strategy === "inline" || decision.strategy === "extension";

    if (adapterModuleIds.has(packageName) && providesModule) {
      diagnostics.push(
        createHostBridgeDiagnostic(
          "host-adapter-not-used",
          packageName,
          `The decision is \`${decision.strategy}\`, which claims the module is provided, but this module id is bridged by the generated JSX runtime adapter — no page object has its shape.`,
        ),
      );
    }

    if (decision.strategy === "host") {
      // An adapter row is not a missing mapping — the module *is* bridged, by
      // generated code rather than by a global — so it is reported once above, as
      // `host-adapter-not-used`, and not again here.
      const bridgedByAdapter = mapping !== undefined && mapping.kind === "jsx-runtime-adapter";

      if (mapping === undefined) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-missing",
            packageName,
            `The decision is \`host\` and the bridge has no mapping for this module id, so it would compile to a reference nothing supplies.`,
          ),
        );
      } else if (!bridgedByAdapter && !hostBridgeModuleIds(mapping).includes(packageName)) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-missing",
            packageName,
            `The mapping for this module covers ${hostBridgeModuleIds(mapping).join(", ")} and not this exact id.`,
          ),
        );
      }
    }

    if (decision.strategy === "inline" && mapping !== undefined && mapping.kind === "host-global") {
      // Scoped to identity-sensitive rows, which is the same line the resolver's
      // `auditHostInlineConflict` draws and for the same reason: a mapping says how a
      // `host` decision compiles, never that the package must be `host`. For a module
      // whose identity is not load-bearing there is nothing shared to split, so a
      // cell-local copy is a legitimate choice — reporting it would turn the presence
      // of a table row into a policy.
      if (mapping.identitySensitive === true) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-module-duplicated",
            packageName,
            `The artifact would carry its own copy of a module decided \`host\` and mapped to "${mapping.globalName}". For an identity-sensitive module this is not a size decision: #5 verified one React object per page whose identity hooks and context dispatch through, so a second copy is observable from every cell.`,
          ),
        );
      }
    }
  }

  return diagnostics;
}

/**
 * Whether the cell's declared preset makes the globals the cell's bridged imports need.
 *
 * Two conditions, and both are needed to keep this from becoming a false positive:
 *
 * - the caller said which preset the cell declares (otherwise the bridge abstains
 *   rather than guessing), and
 * - the artifact actually relies on that mapping's global, as
 *   {@link HostBridgeUsage.presetDependent} defines it — which excludes, in
 *   particular, a module some other decision deliberately bundles.
 *
 * Only the preset-conditional rows. A global recorded as `always` is the guard's
 * business, and its absence is not a per-cell configuration fact.
 */
function auditHostBridgePresetReadiness(
  mappings: readonly HostBridgeMapping[],
  cellPreset: CellPresetLibrary["name"] | undefined,
  usage: HostBridgeUsage,
): readonly HostBridgeDiagnostic[] {
  if (cellPreset === undefined) return [];

  const preset = CELL_PRESET_LIBRARIES.find(candidate => candidate.name === cellPreset);
  if (preset === undefined) {
    // A preset name the runtime contract does not record is a configuration error
    // about the cell, not about an import, so it is reported whether or not the
    // caller said what the artifact uses.
    return [
      createHostBridgeDiagnostic(
        "host-mapping-missing",
        "cell-preset",
        `The cell declares preset "${cellPreset}", which is not one of the presets the runtime contract records.`,
      ),
    ];
  }

  // "The caller did not say what this cell uses" is not "this cell uses nothing".
  if (usage.state === "unstated") return [];

  const diagnostics: HostBridgeDiagnostic[] = [];
  for (const mapping of hostBridgeGlobalMappings(mappings)) {
    if (hostBridgeGlobalIsAlwaysAvailable(mapping)) continue;
    if (!hostBridgeModuleIds(mapping).some(moduleId => usage.presetDependent.has(moduleId))) continue;
    if (preset.providesGlobals.includes(mapping.globalName)) continue;
    diagnostics.push(
      createHostBridgeDiagnostic(
        "host-global-missing",
        mapping.specifier,
        `The cell declares preset "${preset.name}", which does not install "${mapping.globalName}", and the artifact relies on it. #5 records this global's absence as a supported state rather than a broken page, so the generated module binds it as-is and the cell meets an undefined value at the point of use.`,
      ),
    );
  }
  return diagnostics;
}

/** A report block for a CI log or a PR body. */
export function formatHostBridgePlan(plan: HostBridgePlan): string {
  return [
    `Host bridge catalog: ${plan.catalog.length} module id(s): ${plan.catalog.map(entry => entry.moduleId).join(", ")}`,
    `Activations: ${plan.activation}${plan.activation === "unstated" ? " (no decisions or references supplied, so nothing may be wired)" : ""}`,
    `Active interceptions: ${plan.interceptions.map(entry => `${entry.moduleId} (${entry.shape})`).join(", ") || "(none)"}`,
    plan.diagnostics.length === 0
      ? "No bridge diagnostics."
      : `${plan.diagnostics.length} bridge diagnostic(s):\n${formatHostBridgeDiagnostics(plan.diagnostics)}`,
  ].join("\n");
}

/**
 * Every module id the bridge intercepts.
 *
 * Takes the mapping list so a caller comparing a bundle against the bridge is
 * comparing against the same table it planned from, rather than against the
 * shipped default.
 */
export function interceptedHostBridgeModuleIds(
  mappings: readonly HostBridgeMapping[] = HOST_BRIDGE_MAPPINGS,
): readonly string[] {
  return hostBridgeInterceptedModuleIds(mappings);
}

/** The JSX runtime exports a generated adapter must define, re-exported for tests. */
export type HostBridgeAdapterExportName = (typeof JSX_RUNTIME_ADAPTER_EXPORTS)[number];
