/**
 * The compilation projection of #9's host module bridge.
 *
 * Decision source: GitHub Issue #9 — "Spec: host module bridge for React,
 * ReactDOM, antd and built-in globals"
 * (https://github.com/Mang-X/forguncy-react-workspace/issues/9), which is itself
 * downstream of:
 * - #4 "application ownership boundaries and dependency strategy semantics"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/4
 * - #5 "establish the ReactCellType target/runtime contract on Forguncy 12.0.100"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/5
 * - #6 "generated ReactCellType artifact and compiler boundary"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/6
 *
 * `core` owns *which* import is bound to which host identity and *why*. This
 * module owns what the compilation path does with that: the source handed to the
 * bundler in place of a dependency, the guard emitted once per artifact, and the
 * diagnostics the bridge reports about a decision list.
 *
 * Three things here are deliberate, and each is the answer to one of #9's
 * acceptance criteria:
 *
 * 1. **The interception is keyed on the specifier and the generated module is a
 *    pure function of the mapping.** No function in this module takes authored
 *    source as an argument, so there is no code path that could rewrite one (#9:
 *    "Standard source imports remain unchanged") and no place for a
 *    package-specific AST rule to live (#9: "without hardcoding package-specific
 *    AST rewrites"). {@link planHostBridge} derives its interception set by
 *    walking the mapping table, so a new row is the whole of the change.
 * 2. **A required global fails through a structured error, not through
 *    `undefined`.** #5 records `React` and `ReactDOM` as `always` available, so
 *    their absence means the artifact is running somewhere that is not the pinned
 *    target — a state worth failing on with a code an Agent can branch on, rather
 *    than one whose symptom appears wherever the value is first used.
 * 3. **A preset-conditional global does not throw.** #5 measured two cells on one
 *    page disagreeing about the same preset global, so absence is a supported
 *    state. It is reported at build time, when the cell's own preset is known, and
 *    at runtime it stays `undefined` exactly as #5 says it will be.
 *
 * Scope note: this module generates the interposed modules and the guard, and
 * audits a decision list against the table. It does not drive a bundler, assemble
 * an artifact, or emit a diagnostic into #6's artifact report — wiring the bridge
 * into the compile boundary is the compiler MVP's job (#7), and asserting a
 * bridge diagnostic through `CellArtifactDiagnostic` would put two vocabularies in
 * one report before anyone has decided how they compose.
 */

import {
  assertHostBridgeContract,
  CELL_PRESET_LIBRARIES,
  findHostBridgeModuleMapping,
  hostBridgeAdapterMappings,
  hostBridgeGlobalIsAlwaysAvailable,
  hostBridgeGlobalMappings,
  hostBridgeInterceptedModuleIds,
  hostBridgeModuleIds,
  HOST_BRIDGE_DIAGNOSTIC_RULES,
  HOST_BRIDGE_MAPPINGS,
  HostBridgeContractError,
} from "@forguncy-react-workspace/core";
import type {
  CellPresetLibrary,
  DependencyDecision,
  HostBridgeAdapterMapping,
  HostBridgeDiagnosticCode,
  HostBridgeGlobalMapping,
  HostBridgeMapping,
  HostBridgeMappingKind,
  JSX_RUNTIME_ADAPTER_EXPORTS,
} from "@forguncy-react-workspace/core";

// ---------------------------------------------------------------------------
// The generated-module banner
// ---------------------------------------------------------------------------

/**
 * The first line of every module this file generates.
 *
 * The same reasoning #6 gives for the artifact banner: a file a machine composed
 * has to be recognizable as one, or a reviewer reading a bundle cannot tell
 * generated interposition from a dependency that happens to look like it.
 */
export const HOST_BRIDGE_GENERATED_BANNER =
  "/* generated by @forguncy-react-workspace/cell-compiler from the host bridge contract (#9) — do not edit */";

// ---------------------------------------------------------------------------
// Generated runtime error
// ---------------------------------------------------------------------------

/**
 * The error the generated bridge throws.
 *
 * Structured the way an Agent needs it — a stable `code`, the specifier that
 * needed the global, the global's name, and the member when the global exists but
 * the member does not — because #9's third acceptance criterion is a *useful*
 * diagnostic, and a message string is not branchable.
 *
 * The remediation sentence is baked in from `core`'s rule table rather than
 * reworded here, so a runtime failure and its build-time counterpart give the same
 * guidance. That is the point of the shared code vocabulary.
 */
function renderErrorFactory(code: HostBridgeDiagnosticCode): string {
  const rule = HOST_BRIDGE_DIAGNOSTIC_RULES[code];
  return [
    `function __fgcHostBridgeError(specifier, globalName, member) {`,
    `  var target = member === undefined ? globalName : globalName + "." + member;`,
    `  var error = new Error("[host-bridge] ${code}: " + specifier + " is bridged to " + target + ", which is not available. ${rule.remediation}");`,
    `  error.name = "HostBridgeError";`,
    `  error.code = ${JSON.stringify(code)};`,
    `  error.specifier = specifier;`,
    `  error.globalName = globalName;`,
    `  error.member = member === undefined ? null : member;`,
    `  error.fixOwner = ${JSON.stringify(rule.fixOwner)};`,
    `  return error;`,
    `}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Host-global modules
// ---------------------------------------------------------------------------

/**
 * The module the bundler loads in place of a `host`-decided dependency.
 *
 * Two shapes, chosen by #5's availability record rather than by anything written
 * here:
 *
 * - `always` — the global is checked and the module refuses without it. The check
 *   is at module scope on purpose: it is the earliest moment the bridge can tell
 *   that the artifact is not on the target it was compiled for, and the later
 *   alternative is a `TypeError` naming whichever property the cell happened to
 *   touch first.
 * - `after-the-declared-preset-resolves` — the module is the global, whatever it
 *   is. A throw here would make a legal cell illegal: #5 records the same global
 *   as present in one cell and absent in another on one page, because each cell
 *   binds its preset globals at its own render instant.
 *
 * The exported value is the global *itself*, never a wrapper. That is #9's first
 * acceptance criterion expressed in generated code: an interposed module that
 * re-exported through a proxy object would satisfy every functional test and still
 * fail the identity check that matters, since two cells comparing their React
 * objects would no longer see the same one.
 */
export function renderHostBridgeGlobalModule(mapping: HostBridgeGlobalMapping): string {
  const lines = [HOST_BRIDGE_GENERATED_BANNER];

  if (hostBridgeGlobalIsAlwaysAvailable(mapping)) {
    lines.push(
      renderErrorFactory("host-global-missing"),
      `var __fgcHostBridgeValue = globalThis[${JSON.stringify(mapping.globalName)}];`,
      `if (__fgcHostBridgeValue === undefined) {`,
      `  throw __fgcHostBridgeError(${JSON.stringify(mapping.specifier)}, ${JSON.stringify(mapping.globalName)}, undefined);`,
      `}`,
      `module.exports = __fgcHostBridgeValue;`,
    );
  } else {
    lines.push(
      `// #5 records this global as available only once the cell's declared preset has`,
      `// resolved, and as absent otherwise, so an absent value is a supported state.`,
      `module.exports = globalThis[${JSON.stringify(mapping.globalName)}];`,
    );
  }

  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// JSX runtime adapter
// ---------------------------------------------------------------------------

/**
 * The generated JSX runtime adapter.
 *
 * The two-parameter/two-case rule below is the one
 * `MangMax/forguncy-react-library` verified and its regression test exists to keep:
 * `jsx(type, props, key)` and `createElement(type, config, children)` disagree
 * about the third parameter, so the key is never forwarded as the third argument
 * and no third argument is passed when there is no key. `core`'s
 * `JSX_RUNTIME_ADAPTER_RULES` is the contract this code implements; the comments
 * here are the *why* for a reader who has the generated file and not the Spec.
 *
 * Two additions to the verified form, both from #9 rather than from taste:
 *
 * - the host lookup is **lazy**, so evaluating the module while `globalThis.React`
 *   is absent does not throw (`evaluation-must-not-throw`) while a call that
 *   actually needs React fails with the bridge's structured error;
 * - `Fragment` is exposed through a **getter**, because it is a *guarded* member —
 *   #5 never read `React.Fragment` off the host object, so the bridge checks it on
 *   access instead of binding a possibly-undefined snapshot at module load.
 *
 * `jsxs` and `jsxDEV` share the implementation. The dev-only arguments are accepted
 * and ignored: they carry debugging metadata, and reproducing it would mean
 * reimplementing a React-internal surface.
 */
export function renderHostBridgeAdapterModule(mapping: HostBridgeAdapterMapping): string {
  const specifier = mapping.specifier;
  const globalName = "React";
  const createElement = mapping.requiredHostMembers.includes("createElement") ? "createElement" : undefined;

  if (createElement === undefined) {
    throw new HostBridgeContractError(
      `Host bridge adapter "${specifier}" declares no "createElement" among its required host members, so the generated adapter would have nothing to delegate to.`,
    );
  }

  const fragmentGuarded = (mapping.guardedMembers ?? []).includes("Fragment");

  const lines = [
    HOST_BRIDGE_GENERATED_BANNER,
    renderRuntimeErrorDispatcher(),
    ``,
    `function __fgcHostBridgeReact() {`,
    `  var value = globalThis[${JSON.stringify(globalName)}];`,
    `  if (value === undefined) {`,
    `    throw __fgcHostBridgeErrorMissing(${JSON.stringify(specifier)}, ${JSON.stringify(globalName)}, undefined);`,
    `  }`,
    `  return value;`,
    `}`,
    ``,
    `// jsx(type, props, key) — the third parameter is the key, NOT children, and`,
    `// createElement's third parameter IS children. Passing the key through as the`,
    `// third argument sets children to the key and drops the key.`,
    `function __fgcHostBridgeJsx(type, props, key) {`,
    `  var React = __fgcHostBridgeReact();`,
    `  if (key === undefined) {`,
    `    // Exactly two arguments: an explicit undefined third one would take`,
    `    // createElement's children branch and overwrite props.children.`,
    `    return React.${createElement}(type, props);`,
    `  }`,
    `  return React.${createElement}(type, Object.assign({}, props, { key: key }));`,
    `}`,
    ``,
    `module.exports = {`,
    `  jsx: __fgcHostBridgeJsx,`,
    `  jsxs: __fgcHostBridgeJsx,`,
    `  jsxDEV: __fgcHostBridgeJsx,`,
    `};`,
  ];

  if (fragmentGuarded) {
    lines.push(
      ``,
      `// Fragment is a guarded member: #5 did not observe it on the host object, so it`,
      `// is checked on access rather than bound as a snapshot at module load.`,
      `Object.defineProperty(module.exports, "Fragment", {`,
      `  enumerable: true,`,
      `  get: function () {`,
      `    var React = __fgcHostBridgeReact();`,
      `    if (React.Fragment === undefined) {`,
      `      throw __fgcHostBridgeErrorIncompatible(${JSON.stringify(specifier)}, ${JSON.stringify(globalName)}, "Fragment");`,
      `    }`,
      `    return React.Fragment;`,
      `  },`,
      `});`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/**
 * The interposed module for a mapping, whichever kind it is.
 *
 * Dispatch is on `kind`, which is the mapping's declaration of whether a page
 * object has the module's shape. Nothing inspects the specifier to decide.
 */
export function renderHostBridgeModule(mapping: HostBridgeMapping): string {
  return mapping.kind === "host-global"
    ? renderHostBridgeGlobalModule(mapping)
    : renderHostBridgeAdapterModule(mapping);
}

// ---------------------------------------------------------------------------
// The artifact guard
// ---------------------------------------------------------------------------

/**
 * A structured error factory whose code is chosen by name.
 *
 * The guard and the adapter throw from different functions and must not carry two
 * copies of the same string, so they share one dispatcher. Kept separate from
 * {@link renderErrorFactory} because the guard needs both runtime codes available
 * in one scope, while each generated module only ever throws one of them.
 */
function renderRuntimeErrorDispatcher(): string {
  const missing = HOST_BRIDGE_DIAGNOSTIC_RULES["host-global-missing"];
  const incompatible = HOST_BRIDGE_DIAGNOSTIC_RULES["host-global-incompatible"];
  return [
    `function __fgcHostBridgeErrorMissing(specifier, globalName, member) {`,
    `  var target = member === undefined ? globalName : globalName + "." + member;`,
    `  var error = new Error("[host-bridge] host-global-missing: " + specifier + " is bridged to " + target + ", which is not available. ${missing.remediation}");`,
    `  error.name = "HostBridgeError";`,
    `  error.code = "host-global-missing";`,
    `  error.specifier = specifier;`,
    `  error.globalName = globalName;`,
    `  error.member = member === undefined ? null : member;`,
    `  error.fixOwner = ${JSON.stringify(missing.fixOwner)};`,
    `  return error;`,
    `}`,
    `function __fgcHostBridgeErrorIncompatible(specifier, globalName, member) {`,
    `  var target = member === undefined ? globalName : globalName + "." + member;`,
    `  var error = new Error("[host-bridge] host-global-incompatible: " + specifier + " is bridged to " + target + ", which is present but not the recorded identity. ${incompatible.remediation}");`,
    `  error.name = "HostBridgeError";`,
    `  error.code = "host-global-incompatible";`,
    `  error.specifier = specifier;`,
    `  error.globalName = globalName;`,
    `  error.member = member === undefined ? null : member;`,
    `  error.fixOwner = ${JSON.stringify(incompatible.fixOwner)};`,
    `  return error;`,
    `}`,
  ].join("\n");
}

export interface RenderHostBridgeGuardOptions {
  readonly mappings?: readonly HostBridgeMapping[];
  /**
   * The host React version recorded in the lock this build is verified against.
   *
   * Supplying it emits the identity check; omitting it means no identity check was
   * performed for this build, which is a weaker validation and is the reason this
   * is a required field rather than an optional one — a caller has to say which of
   * the two it is doing.
   */
  readonly recordedHostReactVersion: string | undefined;
  /** The specifiers the artifact actually references, when known. */
  readonly referencedSpecifiers?: readonly string[];
}

/**
 * The guard emitted once per artifact, at cell entry.
 *
 * Why a guard *and* per-module checks: the module checks fire at whatever moment
 * the bundler evaluates the interposed module, which is a bundler decision, while
 * the guard fires where the cell begins. For the always-available globals that is
 * the difference between failing before a cell's first statement and failing
 * somewhere inside a generated module.
 *
 * What the guard deliberately does **not** do: report preset-conditional globals.
 * #5 records their absence as a supported per-cell state, so a guard that threw
 * would take a legal cell and break it. Those are build-time diagnostics, where
 * the cell's declared preset is known.
 *
 * `recordedHostReactVersion` is compared as an exact string. #5 measured the host
 * as `React.version === "19.2.7"`, so equality is what the evidence supports; a
 * semver-range comparison here would be a policy nobody has decided yet (#16's
 * territory).
 */
export function renderHostBridgeGuard(options: RenderHostBridgeGuardOptions): string {
  const mappings = options.mappings ?? HOST_BRIDGE_MAPPINGS;
  const referenced =
    options.referencedSpecifiers === undefined ? undefined : new Set(options.referencedSpecifiers);
  const isReferenced = (mapping: HostBridgeMapping): boolean =>
    referenced === undefined || hostBridgeModuleIds(mapping).some(id => referenced.has(id));

  const alwaysAvailable = hostBridgeGlobalMappings(mappings)
    .filter(mapping => hostBridgeGlobalIsAlwaysAvailable(mapping))
    .filter(isReferenced);

  const lines = [
    HOST_BRIDGE_GENERATED_BANNER,
    `// Emitted once per artifact, at cell entry. Required globals fail here; globals`,
    `// whose absence #5 records as a supported state are reported at build time.`,
    renderRuntimeErrorDispatcher(),
    `(function __fgcHostBridgeGuard() {`,
  ];

  for (const mapping of alwaysAvailable) {
    const globalName = JSON.stringify(mapping.globalName);
    const specifier = JSON.stringify(mapping.specifier);
    lines.push(
      `  var __fgc${sanitizeBindingName(mapping.specifier)} = globalThis[${globalName}];`,
      `  if (__fgc${sanitizeBindingName(mapping.specifier)} === undefined) {`,
      `    throw __fgcHostBridgeErrorMissing(${specifier}, ${globalName}, undefined);`,
      `  }`,
    );

    if (mapping.identityField === "hostReactVersion" && options.recordedHostReactVersion !== undefined) {
      lines.push(
        `  // The lock's recorded host identity, checked because #5 verified`,
        `  // \`React.version\` on the injected object and this mapping names`,
        `  // \`hostReactVersion\` as its identity field.`,
        `  if (__fgc${sanitizeBindingName(mapping.specifier)}.version !== ${JSON.stringify(options.recordedHostReactVersion)}) {`,
        `    throw __fgcHostBridgeErrorIncompatible(${specifier}, ${globalName}, "version");`,
        `  }`,
      );
    }
  }

  lines.push(`})();`);
  return `${lines.join("\n")}\n`;
}

/**
 * A specifier turned into something usable inside an identifier.
 *
 * Generated code has to name its locals, and a local named after `react-dom/client`
 * would not parse. Deterministic rather than random so two builds of one plan
 * produce identical source.
 */
function sanitizeBindingName(specifier: string): string {
  return specifier
    .split(/[^0-9A-Za-z]+/)
    .filter(segment => segment.length > 0)
    .map(segment => `${segment[0]?.toUpperCase() ?? ""}${segment.slice(1)}`)
    .join("");
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

/**
 * One bridge finding.
 *
 * `detail` carries the offending value and `code` comes from `core`'s shared
 * vocabulary, so the same code can be reported at build time and thrown at
 * runtime. `member` is separate from `detail` because it is the one part of a
 * message a caller may want to branch on without parsing.
 */
export interface HostBridgeDiagnostic {
  readonly code: HostBridgeDiagnosticCode;
  readonly specifier: string;
  readonly detail: string;
  readonly member?: string;
}

export function createHostBridgeDiagnostic(
  code: HostBridgeDiagnosticCode,
  specifier: string,
  detail: string,
  member?: string,
): HostBridgeDiagnostic {
  return { code, specifier, detail, ...(member === undefined ? {} : { member }) };
}

/** The rule behind a diagnostic, so a report can print guidance without the code. */
export function hostBridgeDiagnosticRule(code: HostBridgeDiagnosticCode) {
  return HOST_BRIDGE_DIAGNOSTIC_RULES[code];
}

/** One line per diagnostic, including what to do about it. */
export function formatHostBridgeDiagnostic(diagnostic: HostBridgeDiagnostic): string {
  const rule = HOST_BRIDGE_DIAGNOSTIC_RULES[diagnostic.code];
  return `${diagnostic.specifier}: [${diagnostic.code}] ${rule.label} — ${diagnostic.detail} (fix owner: ${rule.fixOwner})`;
}

export function formatHostBridgeDiagnostics(diagnostics: readonly HostBridgeDiagnostic[]): string {
  return diagnostics.map(formatHostBridgeDiagnostic).join("\n");
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

export interface HostBridgeInterception {
  readonly specifier: string;
  readonly moduleIds: readonly string[];
  readonly kind: HostBridgeMappingKind;
  readonly mapping: HostBridgeMapping;
  /** The source the bundler loads in place of the dependency. */
  readonly source: string;
  /**
   * Whether the dependency's own implementation must be absent from the artifact.
   *
   * Read off the mapping rather than off the decision, because the reason differs
   * by kind and both reasons are about the mapping: a `host-global` row means the
   * page already has this module, so a bundled copy is a second implementation of
   * something that exists; an adapter row means the *published* module would carry
   * its own React, which is the duplicate the adapter exists to avoid. Either way
   * the flag is the answer to #9's first acceptance criterion at the planning
   * level.
   */
  readonly bundledForbidden: boolean;
}

export interface HostBridgePlan {
  readonly interceptions: readonly HostBridgeInterception[];
  readonly diagnostics: readonly HostBridgeDiagnostic[];
}

export interface PlanHostBridgeOptions {
  readonly mappings?: readonly HostBridgeMapping[];
  /**
   * The decisions the artifact is compiled against.
   *
   * Optional because a plan of the table alone is a legitimate question ("what
   * would be intercepted"), and the diagnostics that need a decision simply do not
   * appear when there is none.
   */
  readonly decisions?: readonly DependencyDecision[];
  /**
   * The preset the cell declares, when known.
   *
   * The input that turns a preset-conditional mapping's absence into a *build*
   * diagnostic instead of a runtime surprise. Omitting it is not the same as
   * declaring `None`: it means the caller did not tell the bridge what the cell
   * declares, and the bridge then reports nothing rather than guessing.
   */
  readonly cellPreset?: CellPresetLibrary["name"];
}

/**
 * What the compilation path does with the bridge, plus what is wrong with it.
 *
 * Built by walking the mapping table, which is #9's fifth acceptance criterion
 * rendered as an implementation rather than as a claim: adding a row adds an
 * interception and its forbidden-bundle flag, and there is no second list to keep
 * in step.
 */
export function planHostBridge(options: PlanHostBridgeOptions = {}): HostBridgePlan {
  const mappings = options.mappings ?? HOST_BRIDGE_MAPPINGS;
  const diagnostics: HostBridgeDiagnostic[] = [];

  // The table's own coherence first. `core`'s guard throws rather than reporting,
  // because an incoherent table is a programming error; here the throw is
  // converted so a caller doing a dry run gets a plan plus a diagnostic instead of
  // an exception that skips the rest of the audit.
  try {
    assertHostBridgeContract(mappings);
  } catch (error) {
    diagnostics.push(
      createHostBridgeDiagnostic(
        "host-mapping-conflict",
        "bridge-mapping-table",
        error instanceof HostBridgeContractError ? error.message : String(error),
      ),
    );
  }

  const interceptions: HostBridgeInterception[] = mappings.map(mapping => ({
    specifier: mapping.specifier,
    moduleIds: hostBridgeModuleIds(mapping),
    kind: mapping.kind,
    mapping,
    // Exactly one generated source per interceptions, so a reader cannot be shown
    // a plan whose source disagrees with the mapping it came from.
    source: renderHostBridgeModule(mapping),
    bundledForbidden: true,
  }));

  // A duplicated claim would make the plan's interception order decide the result,
  // which is the same failure `host-mapping-conflict` reports for the table; the
  // guard above already covers it, and this keeps the check meaningful when a
  // caller passes a table it built itself.
  const seen = new Map<string, string>();
  for (const interception of interceptions) {
    for (const moduleId of interception.moduleIds) {
      const owner = seen.get(moduleId);
      if (owner !== undefined && owner !== interception.specifier) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-conflict",
            moduleId,
            `Both "${owner}" and "${interception.specifier}" intercept this module id, so which source is used would depend on table order.`,
          ),
        );
      }
      seen.set(moduleId, interception.specifier);
    }
  }

  diagnostics.push(...auditHostBridgeDecisions(options.decisions ?? [], mappings));
  diagnostics.push(...auditHostBridgePresetReadiness(mappings, options.cellPreset));

  return { interceptions, diagnostics };
}

/**
 * A decision list against the mapping table.
 *
 * Three questions, each a way a decision and a mapping can disagree:
 *
 * - a `host` decision for a module the table cannot bind;
 * - a JSX runtime id resolved by a page global, when only the adapter has the
 *   module's shape;
 * - a bridged module that the decision bundles anyway, which is the duplicated
 *   identity #9's first acceptance criterion is about.
 */
function auditHostBridgeDecisions(
  decisions: readonly DependencyDecision[],
  mappings: readonly HostBridgeMapping[],
): readonly HostBridgeDiagnostic[] {
  const diagnostics: HostBridgeDiagnostic[] = [];
  const adapterModuleIds = new Set(hostBridgeAdapterMappings(mappings).flatMap(hostBridgeModuleIds));

  for (const decision of decisions) {
    const packageName = decision.packageName;
    const mapping = findHostBridgeModuleMapping(packageName, mappings);
    const providesModule = decision.strategy === "host" || decision.strategy === "inline" || decision.strategy === "extension";

    if (adapterModuleIds.has(packageName) && providesModule) {
      diagnostics.push(
        createHostBridgeDiagnostic(
          "host-adapter-not-used",
          packageName,
          `The decision is \`${decision.strategy}\`, which claims the module is provided, but this module id is bridged by the generated JSX runtime adapter — no page object has its shape.`,
        ),
      );
    }

    if (decision.strategy === "host") {
      // An adapter row is not a missing mapping — the module *is* bridged, by
      // generated code rather than by a global — so it is reported once above, as
      // `host-adapter-not-used`, and not again here.
      const bridgedByAdapter = mapping !== undefined && mapping.kind === "jsx-runtime-adapter";

      if (mapping === undefined) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-missing",
            packageName,
            `The decision is \`host\` and the bridge has no mapping for this module id, so it would compile to a reference nothing supplies.`,
          ),
        );
      } else if (!bridgedByAdapter && !hostBridgeModuleIds(mapping).includes(packageName)) {
        diagnostics.push(
          createHostBridgeDiagnostic(
            "host-mapping-missing",
            packageName,
            `The mapping for this module covers ${hostBridgeModuleIds(mapping).join(", ")} and not this exact id.`,
          ),
        );
      }
    }

    if (decision.strategy === "inline" && mapping !== undefined && mapping.kind === "host-global") {
      const identitySensitive = mapping.identitySensitive === true;
      diagnostics.push(
        createHostBridgeDiagnostic(
          "host-module-duplicated",
          packageName,
          identitySensitive
            ? `The artifact would carry its own copy of a module decided \`host\` and mapped to "${mapping.globalName}". For an identity-sensitive module this is not a size decision: #5 verified one React object per page whose identity hooks and context dispatch through, so a second copy is observable from every cell.`
            : `The artifact would carry its own copy of a module the bridge binds to "${mapping.globalName}", so the cell would use one implementation while the rest of the page uses another.`,
        ),
      );
    }
  }

  return diagnostics;
}

/**
 * Whether the cell's declared preset makes the globals its bridged imports need.
 *
 * Only the preset-conditional mappings, and only when the caller said which preset
 * the cell declares. A mapping whose global the preset does not provide is
 * reported as `host-global-missing` at build time — which is the moment the fact is
 * available — rather than being left to appear as `undefined` at the point of use.
 */
function auditHostBridgePresetReadiness(
  mappings: readonly HostBridgeMapping[],
  cellPreset: CellPresetLibrary["name"] | undefined,
): readonly HostBridgeDiagnostic[] {
  if (cellPreset === undefined) return [];

  const preset = CELL_PRESET_LIBRARIES.find(candidate => candidate.name === cellPreset);
  if (preset === undefined) {
    return [
      createHostBridgeDiagnostic(
        "host-mapping-missing",
        "cell-preset",
        `The cell declares preset "${cellPreset}", which is not one of the presets the runtime contract records.`,
      ),
    ];
  }

  const diagnostics: HostBridgeDiagnostic[] = [];
  for (const mapping of hostBridgeGlobalMappings(mappings)) {
    if (hostBridgeGlobalIsAlwaysAvailable(mapping)) continue;
    if (preset.providesGlobals.includes(mapping.globalName)) continue;
    diagnostics.push(
      createHostBridgeDiagnostic(
        "host-global-missing",
        mapping.specifier,
        `The cell declares preset "${preset.name}", which does not install "${mapping.globalName}". #5 records this global's absence as a supported state rather than a broken page, so the generated module binds it as-is and the cell meets an undefined value at the point of use.`,
      ),
    );
  }
  return diagnostics;
}

/** A report block for a CI log or a PR body. */
export function formatHostBridgePlan(plan: HostBridgePlan): string {
  const intercepted = plan.interceptions.flatMap(interception => interception.moduleIds);
  return [
    `Host bridge intercepts ${intercepted.length} module id(s): ${intercepted.join(", ")}`,
    `Mappings: ${plan.interceptions.map(interception => `${interception.specifier} (${interception.kind})`).join(", ")}`,
    plan.diagnostics.length === 0
      ? "No bridge diagnostics."
      : `${plan.diagnostics.length} bridge diagnostic(s):\n${formatHostBridgeDiagnostics(plan.diagnostics)}`,
  ].join("\n");
}

/**
 * Every module id the bridge intercepts.
 *
 * Takes the mapping list so a caller comparing a bundle against the bridge is
 * comparing against the same table it planned from, rather than against the
 * shipped default.
 */
export function interceptedHostBridgeModuleIds(
  mappings: readonly HostBridgeMapping[] = HOST_BRIDGE_MAPPINGS,
): readonly string[] {
  return hostBridgeInterceptedModuleIds(mappings);
}

/** The JSX runtime exports a generated adapter must define, re-exported for tests. */
export type HostBridgeAdapterExportName = (typeof JSX_RUNTIME_ADAPTER_EXPORTS)[number];
