/**
 * The generated module that installs the host provider inside a Cell.
 *
 * Decision source: GitHub Issue #82 — "修复 Runtime：在生产 Cell 入口自动安装 Host
 * Provider"
 * (https://github.com/Mang-X/forguncy-react-workspace/issues/82), under #81.
 *
 * ## The gap this module closes, and why nothing else could
 *
 * `packages/runtime/src/host-provider.ts` states the requirement and cannot meet it: the
 * values a host provider is built from — `props` and `useDataSource` — are
 * *wrapper-locals* of the arrow IIFE the ReactCellType runtime wraps cell source in
 * (`CELL_SOURCE_EXECUTION_MODEL.userCodeNesting`). They exist in the Cell's lexical scope
 * and nowhere else; `props` is not even a window property. So the package cannot reach
 * them, and `#27` forbids it from sniffing for them. Something *generated into the Cell*
 * has to do the wiring, and this module is that something: `core` declares the contract
 * (`CELL_RUNTIME_BINDING_CONTRACT`), the bundler intercepts the façade specifier, and the
 * source below is what the interception hands back.
 *
 * Before #82 the artifact had no such module, and the failure was invisible from the
 * compile side: a Cell calling `runtimeFacade()` compiled cleanly and threw
 * `provider-not-installed` the moment it ran. The local dev loop could not reveal it
 * either, because `dev-harness` installs a *mock* provider itself — the one path that
 * executed the Cell was the one path that supplied what the artifact lacked.
 *
 * ## Three decisions, each with a reason
 *
 * 1. **The module's own façade import is resolved to an explicit specifier, not left
 *    bare.** This is not a style choice and it was measured. A `\0`-prefixed virtual
 *    module has no directory, so Rolldown resolves a bare specifier in it against the
 *    *process* cwd: from `examples/dev-harness` (where the workspace link exists) it
 *    resolves, and from `packages/cell-compiler` (where it does not) it becomes an
 *    external import — which assembly then refuses, or worse, which ships an artifact
 *    referencing an undefined IIFE parameter and throws a bare `ReferenceError` with no
 *    `code` on the first façade call. Embedding the resolved id is what makes the
 *    generated module's own import land in the same place the authored one does.
 * 2. **The module is ESM, and re-exports the whole façade barrel.** Authored source
 *    imports `runtimeFacade` (and whatever else the façade exports) by name, and the
 *    interception replaces the specifier for *every* importer — so the generated module
 *    has to carry the names the authored imports asked for. `export *` rather than a
 *    hand-written list, for the reason `core/browser` gives about its own projection: a
 *    hand-copied list drifts the first time a name is added to one side and not the
 *    other.
 * 3. **Nothing about the Cell's own capabilities is inspected.** Which addresses a
 *    provider carries is answered when one is asked for (`provider.ts`'s taxonomy), so a
 *    Cell that uses one façade member does not get refused over another it never touches
 *    — #9's rule, and the reason this module does not walk the props.
 *
 * Scope note: this module renders source and declares the names that source references.
 * It does not drive a bundler, decide when the interception applies, or assemble an
 * artifact — `rolldown-bundler.ts` owns the first two and `artifact.ts` the third. What it
 * does own is the answer to "what exactly is generated, and how do we know it only names
 * things a Cell may name", which is why {@link CELL_RUNTIME_BINDING_HOST_NAMES} exists as
 * a declared list rather than a claim in a comment.
 */

import { CELL_RUNTIME_BINDING_CONTRACT, CELL_RUNTIME_BINDING_HOST_NAMES } from "@forguncy-react-workspace/core";

import { cellEntryWrapperNamesAreVerified } from "./entry.ts";

/**
 * The first line of the module this file generates.
 *
 * The same reasoning #6 gives for the artifact banner: a file a machine composed has to be
 * recognizable as one, or a reviewer reading a bundle cannot tell generated wiring from a
 * dependency that happens to look like it.
 */
export const RUNTIME_BINDING_GENERATED_BANNER =
  "/* generated by @forguncy-react-workspace/cell-compiler from the runtime binding contract (#82) — do not edit */";

/**
 * The virtual module id the generated binding is registered under.
 *
 * Fixed and path-free, like the entry shim's: the module exists per build, is never read
 * from disk, and is told apart from authored modules by its `\0` prefix rather than by
 * anything in the id. The *resolved façade specifier* travels inside the module's source,
 * which is where it belongs — an id carrying a machine path would make the id (and so any
 * warning attributed to it) differ between two checkouts of the same project.
 *
 * The prefix is also load-bearing at resolution time: `rolldown-bundler.ts` skips
 * interception for an importer whose id starts with `\0`, which is what keeps this module's
 * own façade import from being replaced by another copy of itself.
 */
export const CELL_RUNTIME_BINDING_ID = "\0cell-runtime-binding";

/**
 * The names the generated binding's source references, re-exported through this module.
 *
 * Derived from `core`'s contract rather than written here, and re-exported rather than
 * reached for through `core` by every caller: the check that keeps these honest
 * ({@link runtimeBindingNamesAreVerified}) belongs beside the template that uses them.
 */
export { CELL_RUNTIME_BINDING_HOST_NAMES };

/**
 * Renders the module that installs a host provider built from the Cell's own values.
 *
 * `facadeSpecifier` is the **resolved** specifier of the façade module — an absolute path
 * in a workspace, or a `node_modules` path in a published install — never the bare package
 * name authored source wrote. See the module header's first decision for why that
 * distinction is load-bearing rather than tidy.
 *
 * The body is deliberately three statements and no control flow. There is no
 * `typeof props !== "undefined"` guard and no environment branch: `props` and
 * `useDataSource` are declared by the platform's own wrapper before the cell source runs,
 * so a guard would be dead code that reads like a supported state, and an environment
 * branch is the second code path `RUNTIME_FACADE_RESOLUTION_MODEL` exists to forbid.
 *
 * Re-installing is safe and deliberate: `installRuntimeFacadeProvider` replaces a provider
 * of the same kind, which is what makes an HMR pass or a re-evaluated module normal rather
 * than a conflict.
 */
export function renderRuntimeBindingModule(facadeSpecifier: string): string {
  const { installMember, createProviderMember, providerInput } = CELL_RUNTIME_BINDING_CONTRACT;
  // JSON rather than a template placeholder: the specifier is a path, and a path on
  // Windows contains backslashes that a naive interpolation would emit as escape
  // sequences inside the generated string literal. `JSON.stringify` produces a literal
  // that parses back to exactly this string in any of the separators Rolldown reports.
  const specifierLiteral = JSON.stringify(facadeSpecifier);
  return [
    RUNTIME_BINDING_GENERATED_BANNER,
    `import * as __fgcRuntimeModule from ${specifierLiteral};`,
    `__fgcRuntimeModule.${installMember}(`,
    `  __fgcRuntimeModule.${createProviderMember}({`,
    `    ${providerInput.cellProps}: props,`,
    `    ${providerInput.useDataSource}: useDataSource,`,
    `  })`,
    `);`,
    `export * from ${specifierLiteral};`,
    ``,
  ].join("\n");
}

/**
 * Whether every name the generated binding references is one a Cell may name.
 *
 * The predicate is `entry.ts`'s, applied to this module's own name list — a generated
 * module that reached for an invented global would ship an artifact that throws
 * `ReferenceError` at evaluation, before React or the façade is involved, and no artifact
 * audit could see it because a free identifier is not an import.
 *
 * The check is one-directional here and its mirror lives in the test: this asks "is every
 * declared name verified", and the test asks "does every declared name actually occur in
 * the rendered source". Together they are what makes the declaration mean something — the
 * first alone would pass for a list of names the template never uses.
 */
export function runtimeBindingNamesAreVerified(
  names: readonly string[] = CELL_RUNTIME_BINDING_HOST_NAMES,
): boolean {
  // `entry.ts`'s predicate rather than a second copy of the rule: "which names a Cell may
  // name" is decided once, by the module that owns the wrapper templates, and the
  // dependency runs one way — `entry.ts` knows nothing about this module.
  return cellEntryWrapperNamesAreVerified(names);
}
