/**
 * `@forguncy-react-workspace/core` — the executable projection of the
 * architecture decisions that every other package must obey.
 *
 * Governing architecture Spec Issues:
 * - #4 "application ownership boundaries and dependency strategy semantics"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/4
 * - #5 "establish the ReactCellType target/runtime contract on Forguncy 12.0.100"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/5
 *
 * Spec Issues built on them:
 * - #8 "reproducible dependency decisions and `fgc.lock.json`"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/8
 * - #16 "Agent-driven dependency selection and empirical compatibility probe"
 *   — https://github.com/Mang-X/forguncy-react-workspace/issues/16
 *
 * Scope note: this package states *semantics, boundaries, verified target facts,
 * the dependency-decision model, and the selection/probe policy*. It intentionally
 * does not resolve dependencies, bundle anything, run a probe, or maintain a
 * package compatibility database; those are separate Issues. Reading and writing
 * `fgc.lock.json` as a project artifact is `dependency-resolver`'s job.
 */

export {
  APPLICATION_OWNERSHIP_INVARIANT,
  assertOwnedBy,
  concernsOwnedBy,
  findOwnershipConcern,
  isApplicationOwned,
  ownerOf,
  OwnershipViolationError,
  OWNERSHIP_CONCERNS,
} from "./ownership";
export type { ApplicationOwner, OwnershipConcern, OwnershipConcernId } from "./ownership";

export {
  DEPENDENCY_REJECTION_KINDS,
  ARCHITECTURAL_REJECTION_CODES,
  DEPENDENCY_REJECTION_RESPONSE,
  groupRejectionsByKind,
  isArchitecturalRejection,
  isArchitecturalRejectionCode,
  isTechnicalRejection,
  isTechnicalRejectionCode,
  TECHNICAL_REJECTION_CODES,
} from "./rejection";
export type {
  ArchitecturalDependencyRejection,
  ArchitecturalRejectionCode,
  DependencyRejection,
  DependencyRejectionCode,
  DependencyRejectionKind,
  DependencyRejectionResponse,
  GroupedRejections,
  TechnicalDependencyRejection,
  TechnicalRejectionCode,
} from "./rejection";

export {
  APPLICATION_OWNED_ROLES,
  assessDependencyRole,
  findPlatformConflictRule,
  isApplicationOwnedRole,
  isPlatformConflict,
  isRoleMismatch,
  PLATFORM_CONFLICT_PACKAGE_NAMES,
  PLATFORM_CONFLICT_RULES,
} from "./platform-conflicts";
export type {
  ApplicationOwnedRole,
  DependencyRole,
  PlatformConflict,
  PlatformConflictAllowed,
  PlatformConflictAssessment,
  PlatformConflictRoleMismatch,
  PlatformConflictRule,
  PlatformConflictUnclassified,
} from "./platform-conflicts";

export {
  assertDependencyDecision,
  checksForLevel,
  DEPENDENCY_STRATEGIES,
  DEPENDENCY_STRATEGY_SEMANTICS,
  isDependencyStrategy,
  requiresRealRuntimeValidation,
  strategySemantics,
  validateDependencyDecision,
  validateDependencyDecisionShape,
  validateDependencyVerification,
} from "./strategy";
export type {
  DependencyCheck,
  DependencyCheckLevel,
  DependencyDecision,
  DependencyStrategy,
  DependencyStrategySemantics,
  DependencyVerificationEvidence,
  ExtensionDependencyDecision,
  HostDependencyDecision,
  InlineDependencyDecision,
  ReplaceDependencyDecision,
} from "./strategy";

export {
  citesDecision,
  citesEveryArchitectureDecision,
  citationPatternsFor,
  DECISION_CITATION_PATTERNS,
  decisionReference,
  DEPENDENCY_LOCK_CITATION_PATTERNS,
  DEPENDENCY_LOCK_DECISION,
  DEPENDENCY_LOCK_DECISION_QUALIFIED_REFERENCE,
  DEPENDENCY_LOCK_DECISION_REFERENCE,
  DEPENDENCY_SELECTION_CITATION_PATTERNS,
  DEPENDENCY_SELECTION_DECISION,
  DEPENDENCY_SELECTION_DECISION_QUALIFIED_REFERENCE,
  DEPENDENCY_SELECTION_DECISION_REFERENCE,
  formatDecisionReference,
  formatGoverningSpecReferenceLine,
  GOVERNING_ARCHITECTURE_DECISIONS,
  GOVERNING_ARCHITECTURE_SPEC_REFERENCE_LINE,
  GOVERNING_SPEC_REFERENCE_LINE,
  OWNERSHIP_AND_DEPENDENCY_DECISION,
  OWNERSHIP_AND_DEPENDENCY_DECISION_QUALIFIED_REFERENCE,
  OWNERSHIP_AND_DEPENDENCY_DECISION_REFERENCE,
  qualifiedDecisionReference,
  RUNTIME_CONTRACT_CITATION_PATTERNS,
  RUNTIME_CONTRACT_DECISION,
  RUNTIME_CONTRACT_DECISION_QUALIFIED_REFERENCE,
  RUNTIME_CONTRACT_DECISION_REFERENCE,
} from "./governance";
export type { ArchitectureDecisionSource } from "./governance";

export {
  CELL_DATA_SOURCE_CONTRACT,
  CELL_ENTRY_RESOLUTION_ORDER,
  CELL_ENTRY_SHAPES,
  CELL_FORGUNCY_FACADE,
  CELL_FORGUNCY_PROP_KEYS,
  CELL_HOST_RUNTIME_SEMANTICS,
  CELL_PRESET_LIBRARIES,
  CELL_PRESET_LIBRARY_DEFAULT,
  CELL_PROPS_BASE_KEYS,
  CELL_PROPS_KEY_ORDER,
  CELL_RUNTIME_RENDER_FAILURE_BEHAVIOR,
  CELL_SERVER_COMMANDS_CONTRACT,
  CELL_SERVER_COMMAND_RESULT_KEYS,
  CELL_SOURCE_EXECUTION_MODEL,
  CELL_SOURCE_REJECTIONS,
  CELL_SOURCE_REJECTION_ENVELOPE,
  CELL_SOURCE_SIZE_OBSERVATIONS,
  CELL_SOURCE_VALIDATION_MECHANISM,
  CELL_USER_SCOPE_BINDINGS,
  cellSourceValidationVisitsAstKey,
  cellUserScopeBinding,
  describeRuntimeContractTarget,
  emitCellEntryShapes,
  findCellEntryShape,
  findCellHostRuntimeFact,
  findCellPresetLibrary,
  findCellSourceRejection,
  FRONTEND_LIBRARY_REFERENCE_CONTRACT,
  FRONTEND_LIBRARY_REFERENCE_EXAMPLE,
  FRONTEND_LIBRARY_RUNTIME_SEMANTICS,
  nonWorkingCellEntryShapes,
  openRuntimeContractQuestions,
  persistedDefaultCellPreset,
  rejectedCellSourceConstructs,
  RUNTIME_CONTRACT_TARGET,
  RUNTIME_CONTRACT_UNKNOWNS,
  RUNTIME_EVIDENCE_CHANNELS,
} from "./runtime-contract";
export type {
  CellBindingAvailability,
  CellEntryKind,
  CellEntryResolutionStep,
  CellEntryShape,
  CellHostRuntimeFact,
  CellHostRuntimeFactId,
  CellPresetLibrary,
  CellSourceExecutionModel,
  CellSourceRejection,
  CellSourceRejectionId,
  CellSourceValidationMechanism,
  CellUserScopeBinding,
  FrontendLibraryReference,
  RuntimeContractTarget,
  RuntimeContractUnknown,
  RuntimeEvidenceChannel,
} from "./runtime-contract";

export {
  assertFgcLockDocument,
  assertFgcLockDocumentShape,
  assertSupportedFgcLockSchemaVersion,
  canonicalizeFgcLock,
  compareEvidenceLinks,
  compareLockDecisions,
  createEmptyFgcLock,
  DECISION_EVIDENCE_KINDS,
  dependencyDecisionOf,
  FGC_LOCK_FILE_NAME,
  FGC_LOCK_SCHEMA_VERSION,
  FgcLockSchemaVersionError,
  FgcLockValidationError,
  findMachineSpecificPaths,
  forguncyTargetIdentity,
  inspectFgcLockDocument,
  isCanonicallyOrdered,
  isEvidenceReference,
  isEvidenceUrl,
  isRepositoryRelativeReference,
  isSupportedFgcLockSchemaVersion,
  LOCK_EVIDENCE_POLICY,
  LOCK_EVIDENCE_PROFILES,
  LOCK_GOVERNING_DECISIONS,
  LOCK_GOVERNING_SPEC_REFERENCE_LINE,
  LOCK_PROBE_REQUIREMENTS,
  lockEvidencePolicyFor,
  lockEvidenceProfileForDecision,
  lockEvidenceProfileOf,
  matchesForguncyTargetIdentity,
  parseFgcLockDocument,
  PROBE_STATUSES,
  requiresRuntimeValidation,
  requiresTargetIdentity,
  RUNTIME_CONFIRMED_TECHNICAL_REJECTION_CODES,
  serializeFgcLock,
  SUPPORTED_FGC_LOCK_SCHEMA_VERSIONS,
  validateFgcLockDocument,
} from "./lock";
export type {
  DecisionEvidenceKind,
  DecisionEvidenceLink,
  ExtensionEvidence,
  FgcLockDocument,
  ForguncyTargetIdentity,
  LockedDependencyDecision,
  LockEvidencePolicy,
  LockEvidenceProfile,
  LockProbeEvidence,
  LockProbeRequirement,
  LockRecordMetadata,
  ProbeStatus,
  RejectedCandidateEvidence,
  ToolchainIdentity,
} from "./lock";

export {
  FGC_LOCK_MIGRATION_STEPS,
  findFgcLockMigrationStep,
  FgcLockMigrationError,
  FgcLockMigrationStepError,
  migrateFgcLockDocument,
  migratableFgcLockSchemaVersions,
  parseMigratedFgcLockDocument,
  planFgcLockMigration,
  validateFgcLockMigrationSteps,
} from "./lock-migration";
export type { FgcLockMigrationOptions, FgcLockMigrationResult, FgcLockMigrationStep } from "./lock-migration";

export {
  assessLockDecision,
  findLockDecision,
  LOCK_FRESHNESS_STATES,
  LOCK_REAL_RUNTIME_VALIDATIONS,
  LOCK_STALENESS_REASONS,
  lockDecisionBlockers,
  resolveLockDecision,
} from "./lock-freshness";
export type {
  LockDecisionAssessment,
  LockDecisionQuery,
  LockDecisionResolution,
  LockDecisionState,
  LockEnvironment,
  LockFreshness,
  LockRealRuntimeValidation,
  LockStalenessReason,
} from "./lock-freshness";

// #16 — dependency selection: what makes a package a good candidate, what a probe
// must observe, and in what order the Agent is allowed to decide anything.

export {
  decideFromSignals,
  findReplacementSignalRejection,
  findSelectionSignal,
  isSelectionSignalFamily,
  isSelectionSignalId,
  MACHINE_OBSERVED_SIGNAL_INVARIANT,
  NON_EVIDENCE_SIGNAL_SOURCES,
  replacementRejectionFor,
  REPLACEMENT_SIGNAL_REJECTIONS,
  SELECTION_SIGNALS,
  SELECTION_SIGNAL_FAMILIES,
  SELECTION_SIGNAL_FAMILY_SEMANTICS,
  SELECTION_SIGNAL_IDS,
  selectionSignal,
  selectionSignalFamilyOf,
  selectionSignalFamilySemantics,
  selectionSignalsObservedFrom,
  SIGNAL_OBSERVATION_CHANNELS,
  signalsInFamily,
  validateSignalFindings,
} from "./selection-signals";
export type {
  NonEvidenceSignalSource,
  ReplacementSignalRejection,
  SelectionSignal,
  SelectionSignalFamily,
  SelectionSignalFamilySemantics,
  SelectionSignalFinding,
  SelectionSignalId,
  SignalObservationChannel,
  SignalVerdict,
} from "./selection-signals";

export {
  assessProbeReport,
  assertProbeReport,
  assertSupportedProbeReportSchemaVersion,
  canonicalizeProbeReport,
  executedProbeSteps,
  findForbiddenProbeKeys,
  findProbeStep,
  FORBIDDEN_PROBE_REPORT_KEYS,
  hasPassingEvidence,
  inspectProbeReport,
  isProbeStepId,
  isSupportedProbeReportSchemaVersion,
  parseProbeReport,
  PROBE_ASSESSMENT_STATUSES,
  PROBE_DEPLOYMENT_REQUIRED_STEPS,
  PROBE_ENGINE_NON_RESPONSIBILITIES,
  PROBE_EVIDENCE_POLICY,
  PROBE_OUTCOMES,
  probeRisksOf,
  PROBE_REPORT_MACHINE_READABILITY,
  PROBE_REPORT_SCHEMA_VERSION,
  PROBE_REPORT_SECTIONS,
  PROBE_STEPS,
  PROBE_STEPS_OBSERVING_SIGNAL,
  PROBE_STEP_IDS,
  ProbeReportSchemaVersionError,
  ProbeReportValidationError,
  probeStep,
  probeStepObservesSignal,
  probeStepOrder,
  probeStepsObserving,
  probeSupportsDeployment,
  serializeProbeReport,
  signalObservesForguncyTarget,
  SUPPORTED_PROBE_REPORT_SCHEMA_VERSIONS,
  validateProbeReport,
} from "./probe-protocol";
export type {
  ProbeAssessment,
  ProbeAssessmentStatus,
  ProbeEngineNonResponsibility,
  ProbeEngineNonResponsibilityId,
  ProbeEnvironment,
  ProbeFact,
  ProbeOutcome,
  ProbeRejectionFinding,
  ProbeReport,
  ProbeReportSection,
  ProbeRisk,
  ProbeStep,
  ProbeStepId,
  ProbeValidationEntry,
} from "./probe-protocol";

export {
  ARCHITECTURAL_REJECTION_PROBE_STATUS,
  auditSelectionDecision,
  branchForOwnership,
  CONDITIONAL_SELECTION_STAGES,
  evaluateRepairRecipe,
  findConditionalSelectionStage,
  findSelectionBranch,
  findSelectionStage,
  isConditionalSelectionStage,
  isOwnershipGateFirst,
  isSelectionBranchId,
  isSelectionDecisionRecordable,
  isSelectionStageId,
  lockProbeStatusForAssessment,
  NO_PACKAGE_ADAPTER_REGISTRY_INVARIANT,
  OWNERSHIP_GATE_STAGE_ID,
  probeSupportsStrategy,
  REPAIR_RECIPE_CONDITIONS,
  SELECTION_ACCEPTANCE_CRITERIA,
  SELECTION_AUTHORITIES,
  SELECTION_BRANCHES,
  SELECTION_GOVERNING_DECISIONS,
  SELECTION_GOVERNING_SPEC_REFERENCE_LINE,
  SELECTION_STAGES,
  SELECTION_STAGE_IDS,
  selectionBranch,
  selectionJustificationRequired,
  selectionStage,
  selectionStageOrder,
  SPEC_PROVING_CASES,
  stagesBefore,
  stagesForBranch,
  stagesForIslandDecision,
  stagesSkippedOnEarlyExit,
  stagesWithAuthority,
} from "./selection-policy";
export type {
  ConditionalSelectionStage,
  RepairRecipeAssessment,
  RepairRecipeCondition,
  RepairRecipeConditionId,
  RepairRecipeInput,
  SelectionAcceptanceCriterion,
  SelectionAuditInput,
  SelectionAuthority,
  SelectionBranch,
  SelectionBranchId,
  SelectionStage,
  SelectionStageId,
  SpecProvingCase,
  StrategyProbeSupport,
} from "./selection-policy";
