import { REPO, STATUS, labelsOf, isDone, issueType, priority, buildModel, walk, layout, promptFor } from './model.mjs';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COLORS={ready:'#4b996f',blocked:'#c29067',active:'#668fca',done:'#93ae9c',cancelled:'#aaaab0',review:'#bca15e',epic:'#a58ebc'};
const TYPE_NAMES={epic:'计划',spec:'规格',feature:'实施',research:'研究',infra:'工程',docs:'文档',issue:'任务'};
const AREA_NAMES={compiler:'编译器',runtime:'运行时',dependency:'依赖',mcp:'MCP',skill:'Skill',dev:'开发体验'};
const KEY=`fgc-board:${REPO}:v1`;
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
let snapshot;
try{snapshot=JSON.parse($('snapshot').textContent);}catch{snapshot=null;}
const cached=load(KEY+':data',null);
if(cached?.repo===REPO && (!snapshot||Date.parse(cached.fetchedAt)>Date.parse(snapshot.fetchedAt))) snapshot=cached;
if(snapshot?.repo!==REPO) snapshot=null;
let model=buildModel(snapshot?.records||[],snapshot?.native||{},snapshot?.incomplete||[]);
let assignments=load(KEY+':assignments',{}), selected=null, view='graph', statusFilter='',search='',typeFilter='',areaFilter='',hideClosed=false, focus=false;
let origin=snapshot?'内置 / 本地快照':'等待首次同步', syncing=false, syncError='', nextAllowed=0, apiRemaining=null;
let transform={x:12,y:15,scale:.88},graphLayout=layout(model), currentVisible=[], toastTimer;
const localReserved=i=>Boolean(assignments[i.number]?.agent?.trim());
const available=()=>model.issues.filter(i=>i.status==='ready'&&!localReserved(i)).sort((a,b)=>priority(a)-priority(b)||(model.outgoing.get(b.number)?.length||0)-(model.outgoing.get(a.number)?.length||0)||a.number-b.number);
const issueURL=n=>`https://github.com/${REPO}/issues/${Number(n)}`;
const shortDate=t=>t?new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'未同步';
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3300);}
function badge(i){return `<span class="badge ${i.status}"><span class="dot ${i.status}"></span>${STATUS[i.status]}</span>`;}
function currentFilters(i){return (!statusFilter||i.status===statusFilter)&&(!typeFilter||issueType(i)===typeFilter)&&(!areaFilter||labelsOf(i).includes('area:'+areaFilter))&&(!hideClosed||i.state!=='closed')&&(!search||`#${i.number} ${i.title} ${labelsOf(i).join(' ')} ${(i.assignees||[]).map(a=>a.login).join(' ')}`.toLowerCase().includes(search));}
function choose(n){selected=model.byId.has(Number(n))?Number(n):null;focus=false;renderGraph();renderInspector();}
function renderStats(){
  const total=model.issues.length,done=model.issues.filter(isDone).length,ready=available().length,blocked=model.issues.filter(i=>i.status==='blocked').length,active=model.issues.filter(i=>i.status==='active').length;
  $('stats').innerHTML=[['全部任务',total,'所有 Issue · 不含 PR','◇',''],['待分配',ready,'前置已满足 · 本机未分配','↗','ready'],['依赖阻塞',blocked,`${model.edges.filter(e=>e.kind==='hard').length} 条明确前置关系`,'⑂','blocked'],['已完成',done,`${active} 项进行中 · ${total?Math.round(done/total*100):0}% 完成`,'✓','done']].map(([t,n,sub,icon,f],idx)=>`<button class="stat" data-filter="${f}"><div class="stat-top">${t}<span class="stat-icon">${icon}</span></div><strong>${snapshot?n:'—'}</strong><small>${sub}</small>${idx===3?`<span class="stat-meter"><i style="width:${total?done/total*100:0}%"></i></span>`:''}</button>`).join('');
  $('statuses').innerHTML=[['','全部任务'],...Object.entries(STATUS).filter(([k])=>k!=='epic')].map(([k,label])=>`<button class="nav-item ${statusFilter===k?'active':''}" data-filter="${k}"><span class="dot ${k||'epic'}"></span>${label}<b>${k?model.issues.filter(i=>i.status===k).length:total}</b></button>`).join('');
  $('warning-count').textContent=model.warnings.length;
}
function renderSelects(){for(const [id,prefix,names,current]of [['type-filter','type:',TYPE_NAMES,typeFilter],['area-filter','area:',AREA_NAMES,areaFilter]]){const values=[...new Set(model.issues.flatMap(i=>labelsOf(i).filter(l=>l.startsWith(prefix)).map(l=>l.slice(prefix.length))))].sort();$(id).innerHTML=`<option value="">全部${id==='type-filter'?'类型':'领域'}</option>`+values.map(x=>`<option value="${esc(x)}">${esc(names[x]||x)}</option>`).join('');$(id).value=current;}}
function renderSync(){
  const old=snapshot&&Date.now()-Date.parse(snapshot.fetchedAt)>600000;
  $('refresh').disabled=syncing;
  $('refresh-icon').className=syncing?'spin':'';
  $('sync-status').textContent=syncing?'正在同步…':snapshot?`${syncError?'同步失败 · ':origin==='GitHub 已同步'?'已同步 · ':'快照 · '}${shortDate(snapshot.fetchedAt)}`:'尚未获取 GitHub 数据';
  $('sync-status').title=apiRemaining!==null?`本 IP 当前 API 剩余请求：${apiRemaining}。${snapshot?'最后成功读取：'+snapshot.fetchedAt:''}`:'';
  $('data-origin').textContent=origin;
  const warnings=syncError || (old?'当前显示旧快照；完成同步后才可据此分配新任务。':snapshot?.incomplete?.length?`Issue 状态已读取，但 ${snapshot.incomplete.length} 项原生依赖未读取，已标为需核对。`:origin!=='GitHub 已同步'?'先显示上次快照，正在尝试连接 GitHub；请核对同步时间。':'');
  $('notice').hidden=!warnings;$('notice').className='notice'+(syncError?' error':'');$('notice').textContent=warnings;
}
function visibleIssues(){let result=model.issues.filter(currentFilters);if(focus&&selected){const set=new Set([selected,...walk(model,selected,'up'),...walk(model,selected,'down')]);result=result.filter(i=>set.has(i.number));}return result;}
function wrap(text,limit=32,lines=3){const words=text.replace(/^(?:Implement|Spec|Research|Chore|Docs|Epic gate|Epic|Bootstrap):\s*/i,'').split(/\s+/),out=[];let row='';for(const word of words){if((row+' '+word).length>limit&&row){out.push(row);row=word;}else row+=(row?' ':'')+word;}if(row)out.push(row);const rows=[];for(const s of out){if(s.length>limit*1.4){for(let j=0;j<s.length;j+=limit)rows.push(s.slice(j,j+limit));}else rows.push(s);}if(rows.length>lines){rows.length=lines;rows[lines-1]=rows[lines-1].slice(0,limit-1)+'…';}return rows;}
function renderGraph(){
  $('graph-panel').hidden=view!=='graph';$('queue-panel').hidden=view!=='queue';$('warnings-panel').hidden=view!=='warnings';
  currentVisible=visibleIssues();graphLayout=layout(model,currentVisible);const pos=graphLayout.positions;
  const allRelated=selected?new Set([selected,...walk(model,selected,'up'),...walk(model,selected,'down')]):null;
  const graphEdges=model.edges.filter(e=>pos.has(e.from)&&pos.has(e.to));
  const columns=[...new Set(currentVisible.map(i=>i.level))].sort((a,b)=>a-b);
  let html=columns.map(n=>`<text class="graph-column" x="${36+n*284}" y="30">${n===0?'起点 / 独立任务':`依赖层 ${String(n).padStart(2,'0')}`}</text>`).join('');
  html+=graphEdges.map(e=>{const a=pos.get(e.from),b=pos.get(e.to),x=a.x+a.w,y=a.y+a.h/2,x2=b.x,y2=b.y+b.h/2;let d;if(x2>x)d=`M${x},${y}C${x+28},${y} ${x2-28},${y2} ${x2},${y2}`;else d=`M${x},${y}C${x+50},${y} ${x2+50},${y2} ${x2+b.w},${y2}`;const hl=allRelated&&allRelated.has(e.from)&&allRelated.has(e.to);return `<path class="edge ${e.kind} ${allRelated?(hl?'focus':'dim'):''}" d="${d}"><title>${esc(`${e.from} → ${e.to}: ${e.evidence.map(x=>x.text).join(' / ')}`)}</title></path>`;}).join('');
  html+=currentVisible.map(i=>{const p=pos.get(i.number), color=COLORS[i.status],ls=labelsOf(i),tp=TYPE_NAMES[issueType(i)]||issueType(i);const text=wrap(i.title);const assigned=assignments[i.number]?.agent;const area=ls.find(l=>l.startsWith('area:'))?.slice(5);return `<g class="node ${i.status} ${selected===i.number?'selected':''} ${allRelated&&!allRelated.has(i.number)?'dim':''} ${i.inCycle?'cycle':''}" data-issue="${i.number}" transform="translate(${p.x},${p.y})" tabindex="0" role="button" aria-label="Issue ${i.number} ${esc(i.title)} ${STATUS[i.status]}"><title>#${i.number} ${esc(i.title)}</title><rect class="card-bg" width="${p.w}" height="${p.h}" rx="8"/><circle cx="16" cy="17" r="3" fill="${color}"/><text class="node-id" x="26" y="20">#${i.number}</text><text class="node-type" x="218" y="20" text-anchor="end">${esc(tp)}${priority(i)<3?' · P'+priority(i):''}</text>${text.map((t,k)=>`<text class="node-title" x="13" y="${42+k*14}">${esc(t)}</text>`).join('')}<text class="node-state" x="13" y="93" fill="${color}">${STATUS[i.status]}</text><text class="node-info" x="222" y="93" text-anchor="end">${esc(assigned?'本机: '+assigned.slice(0,12):i.blockers.length?i.blockers.length+' 个前置未满足':i.needsValidation?'需要真实环境':AREA_NAMES[area]||area||'—')}</text></g>`;}).join('');
  $('world').innerHTML=html;setTransform();$('empty-graph').hidden=currentVisible.length>0;
  $('visible-count').textContent=`${currentVisible.length} / ${model.issues.length} 个任务 · ${graphEdges.length} 条连线`;
  $('view-description').textContent=focus?`#${selected} 的上下游依赖链`:'箭头由前置任务指向下游任务';
  $('graph-panel').hidden=view!=='graph';$('queue-panel').hidden=view!=='queue';$('warnings-panel').hidden=view!=='warnings';
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  renderList();renderWarnings();
}
function setTransform(){const {x,y,scale}=transform;$('world').setAttribute('transform',`translate(${x} ${y}) scale(${scale})`);$('zoom-value').textContent=Math.round(scale*100)+'%';const {positions,width,height}=graphLayout;$('minimap').setAttribute('viewBox',`0 0 ${width} ${height}`);const box=$('graph').getBoundingClientRect();$('minimap').innerHTML=[...positions].map(([n,p])=>`<rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" rx="4" fill="${COLORS[model.byId.get(n).status]}" opacity=".45"/>`).join('')+`<rect x="${-x/scale}" y="${-y/scale}" width="${box.width/scale}" height="${box.height/scale}" fill="#48815c0d" stroke="#649879" stroke-width="${Math.max(3,width/140)}"/>`;}
function zoom(factor,cx,cy){const r=$('graph').getBoundingClientRect();cx??=r.width/2;cy??=r.height/2;const old=transform.scale,n=Math.max(.14,Math.min(1.8,old*factor));transform.x=cx-(cx-transform.x)*n/old;transform.y=cy-(cy-transform.y)*n/old;transform.scale=n;setTransform();}
function fit(){const r=$('graph').getBoundingClientRect();transform.scale=Math.max(.14,Math.min(1,(r.width-35)/graphLayout.width,(r.height-80)/graphLayout.height));transform.x=14;transform.y=12;setTransform();}
function centerIssue(n){const p=graphLayout.positions.get(n);if(!p)return;const r=$('graph').getBoundingClientRect();transform.scale=.93;transform.x=r.width/2-(p.x+p.w/2)*transform.scale;transform.y=r.height/2-(p.y+p.h/2)*transform.scale;setTransform();}
function renderList(){const list=[...currentVisible].sort((a,b)=>{const ord={ready:0,active:1,review:2,blocked:3,epic:4,cancelled:5,done:6};return ord[a.status]-ord[b.status]||priority(a)-priority(b)||a.number-b.number;});$('list-title').textContent=(statusFilter?STATUS[statusFilter]:'所有')+'任务';$('task-list').innerHTML=list.length?list.map(i=>`<article class="task-row" data-issue="${i.number}" role="button" tabindex="0"><span class="issue-ref">#${i.number}</span><div><strong>${esc(i.title)}</strong><div class="row-sub">${esc(TYPE_NAMES[issueType(i)]||issueType(i))} · ${priority(i)<3?'P'+priority(i):'未设优先级'} · ${i.blockers.length} 个未完成前置 · 更新 ${shortDate(i.updated_at)}</div></div><div class="row-badges">${assignments[i.number]?.agent?`<span class="badge local">本机：${esc(assignments[i.number].agent)}</span>`:''}${badge(i)}</div></article>`).join(''):'<div class="empty-state"><strong>没有匹配的任务</strong><p>请调整搜索或筛选条件。</p></div>';}
function renderWarnings(){$('warnings-list').innerHTML=model.warnings.length?model.warnings.map(w=>`<div class="warning-row" role="button" tabindex="0" data-issue="${w.issue}"><strong>#${w.issue} · ${esc(w.message)}</strong><code>${esc(w.text)}</code></div>`).join(''):'<div class="empty-state"><span>✓</span><strong>没有检测到依赖异常</strong><p>这只表示明确声明可解析，不代表所有业务前提都已记录。</p></div>';}
function depHTML(e,direction='up'){const n=direction==='up'?e.from:e.to,i=model.byId.get(n);return `<div class="dep-row" ${i?`data-issue="${n}" tabindex="0" role="button"`:''}><div class="dep-row-top"><span class="dot ${i?.status||'review'}"></span><span class="issue-ref">${typeof n==='number'?'#':''}${esc(n)}</span><span class="badge ${e.kind==='hard'?'neutral':'review'}">${e.kind==='hard'?'前置':'条件 / 验收'}</span></div><div class="dep-title">${esc(i?.title||'跨仓库或未读取的 Issue，状态未知')}</div><div class="evidence">${e.evidence.map(v=>`${v.source==='native'?'GitHub 原生':'正文 #'+v.issue} · ${esc(v.text)}`).join('<br>')}</div></div>`;}
function renderInspector(){const panel=$('inspector'),i=model.byId.get(selected);panel.classList.toggle('empty',!i);if(!i){panel.innerHTML='<div class="empty-state"><span>◇</span><strong>从图中选择一个任务</strong><p>查看依赖、原始规格和分配备忘。</p></div>';return;}
  const a=assignments[i.number]||{},deps=model.incoming.get(i.number)||[],down=model.outgoing.get(i.number)||[],parents=model.parentMap.get(i.number)||[];
  const reasons={ready:'明确的前置依赖已完成，未发现人工阻塞。分配前仍需核对真实环境与任务范围。',blocked:`${i.blockers.length} 项硬依赖尚未完成或状态未知。不要跳过前置任务。`,active:'检测到进行中标签或带关闭关联的开放 PR。负责人字段本身不代表已经开工。',done:'GitHub Issue 已关闭，关闭原因为完成（或旧记录未提供原因）。',cancelled:'Issue 已关闭但未标记完成，不自动满足下游前置条件。',review:'存在人工阻塞标签、未解析声明或未读取关系。请核对源 Issue 后再分配。',epic:'这是汇总计划，不把 Epic 当作可直接派给代理的实施任务。'};
  panel.innerHTML=`<div class="inspector-top"><span class="issue-ref">ISSUE #${i.number}</span><span> / ${esc(TYPE_NAMES[issueType(i)]||issueType(i))}</span><button class="close-inspector" data-action="close" aria-label="关闭详情">×</button></div><h2>${esc(i.title)}</h2>${badge(i)}${i.needsValidation?' <span class="badge neutral">真实环境验证</span>':''}<p class="reason ${['blocked','review'].includes(i.status)?'warn':''}">${reasons[i.status]}</p><div class="detail-actions"><button class="button primary" data-action="copy">复制代理任务 ↗</button><a class="button" href="${issueURL(i.number)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div><div class="meta-row"><span>GitHub 负责人</span><b>${esc((i.assignees||[]).map(x=>x.login).join(', ')||'未分配')}</b></div><div class="meta-row"><span>更新时间</span><b>${shortDate(i.updated_at)}</b></div>${parents.length?`<div class="meta-row"><span>所属计划（非阻塞）</span><b>${parents.map(n=>`<a href="${issueURL(n)}" target="_blank" rel="noopener noreferrer">#${n}</a>`).join(' / ')}</b></div>`:''}<div class="tags">${labelsOf(i).map(l=>`<span class="tag">${esc(l)}</span>`).join('')}</div>${i.prs.length?`<div class="detail-section"><h3>关联 PR <span>${i.prs.length}</span></h3>${i.prs.map(p=>`<a class="dep-row" style="display:block" href="https://github.com/${REPO}/pull/${p.number}" target="_blank" rel="noopener noreferrer"><span class="issue-ref">PR #${p.number}</span><div class="dep-title">${esc(p.title)}</div><div class="evidence">${p.pull_request.merged_at?'已合并':p.state==='open'?'开放中':'已关闭未合并'} · ${p.closing?'关闭关联':'引用，不推断开工'}</div></a>`).join('')}</div>`:''}<div class="detail-section"><h3>前置与条件依赖 <span>${deps.length}</span></h3>${deps.length?deps.map(e=>depHTML(e)).join(''):'<p class="empty-note">没有解析到明确的依赖编号。</p>'}<button class="button ghost small" data-action="focus">${focus?'显示全部任务':'只看相关依赖链'}</button></div><div class="detail-section"><h3>直接下游 <span>${down.length}</span></h3>${down.length?down.map(e=>depHTML(e,'down')).join(''):'<p class="empty-note">暂无明确声明的下游。</p>'}</div><div class="detail-section"><h3>分配给代理 <span>仅此浏览器</span></h3><label class="field-label" for="agent-name">代理 / Worktree 名称</label><input class="field-input" id="agent-name" placeholder="例如 Codex-01 / Claude-02" maxlength="80" value="${esc(a.agent||'')}"><label class="field-label" for="agent-note">分配备注</label><textarea class="field-input" id="agent-note" placeholder="负责的范围、分支或注意事项" maxlength="1200">${esc(a.note||'')}</textarea><p class="assignment-help">本机备忘不写回 GitHub、不启动代理，也不改变 Issue 状态。跨设备请导出分配记录。</p><div class="save-row"><button class="button" data-action="save">保存本机分配</button><button class="button ghost danger" data-action="unassign">清除</button></div></div><div class="detail-section"><details class="body-details"><summary>查看 Issue 原始规格与验收标准</summary><pre class="body-source">${esc(i.body||'（无正文）')}</pre></details></div>`;
}
function render(){renderStats();renderSelects();renderGraph();renderInspector();renderSync();}
function setFilter(value){statusFilter=value;focus=false;renderStats();renderGraph();}
function setView(v){view=v;renderGraph();}
async function copy(text){try{if(!navigator.clipboard)throw Error('clipboard');await navigator.clipboard.writeText(text);toast('已复制，可以交给代理执行');}catch{$('copy-text').value=text;$('copy-dialog').showModal();$('copy-text').focus();$('copy-text').select();}}
const responses=new Map();
async function request(url){if(!url.startsWith('https://api.github.com/repos/'+REPO+'/'))throw Error('拒绝非仓库 API 地址');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const old=responses.get(url),headers={Accept:'application/vnd.github+json'};if(old?.etag)headers['If-None-Match']=old.etag;const r=await fetch(url,{headers,signal:controller.signal,credentials:'omit'});apiRemaining=r.headers.get('x-ratelimit-remaining')??apiRemaining;if(r.status===304&&old)return old;if(!r.ok){const reset=Number(r.headers.get('x-ratelimit-reset'));if(r.status===403||r.status===429){nextAllowed=Math.max(Date.now()+180000,reset*1000||0);throw Error(`GitHub API 限流或拒绝访问（${r.status}）；保留上次快照，${shortDate(nextAllowed)} 后重试。`);}throw Error(`GitHub API 返回 ${r.status}，保留上次成功快照。`);}const result={data:await r.json(),etag:r.headers.get('etag'),link:r.headers.get('link')||''};responses.set(url,result);return result;}finally{clearTimeout(timeout);}}
async function paginated(url){const out=[];let count=0;while(url){if(++count>100)throw Error('分页超出安全上限，未用不完整数据覆盖快照。');const r=await request(url);if(!Array.isArray(r.data))throw Error('GitHub 数据格式错误');out.push(...r.data);url=r.link.match(/<([^>]+)>;\s*rel="next"/)?.[1]||'';}return out;}
async function sync(){if(syncing)return;if(Date.now()<nextAllowed){toast('API 冷却中，请在 '+shortDate(nextAllowed)+' 后重试');return;}syncing=true;renderSync();try{
  const records=await paginated(`https://api.github.com/repos/${REPO}/issues?state=all&per_page=100&sort=created&direction=asc`),native={},incomplete=[];
  for(const i of records.filter(i=>!i.pull_request)){
    const count=i.issue_dependencies_summary?.total_blocked_by;
    if(count===0){native[i.number]=[];continue;}
    if(count===undefined){incomplete.push(i.number);continue;}
    const prev=snapshot?.records?.find(p=>p.number===i.number);
    if(prev?.updated_at===i.updated_at&&prev?.issue_dependencies_summary?.total_blocked_by===count&&snapshot.native?.[i.number]){native[i.number]=snapshot.native[i.number];continue;}
    try{native[i.number]=await paginated(`https://api.github.com/repos/${REPO}/issues/${i.number}/dependencies/blocked_by?per_page=100`);}catch{incomplete.push(i.number);}
  }
  snapshot={repo:REPO,fetchedAt:new Date().toISOString(),records,native,incomplete};model=buildModel(records,native,incomplete);save(KEY+':data',snapshot);origin='GitHub 已同步';syncError='';if(!selected&&window.innerWidth>760)selected=available()[0]?.number||model.issues[0]?.number||null;render();
}catch(e){syncError=e.name==='AbortError'?'连接 GitHub 超时；保留上次成功快照。':e.message||'连接 GitHub 失败；请检查网络。';if(snapshot)origin='快照回退 · 非实时';renderSync();}finally{syncing=false;renderSync();}}
document.addEventListener('click',e=>{const target=e.target.closest('[data-issue]');if(target){choose(target.dataset.issue);if(target.classList.contains('dep-row'))centerIssue(Number(target.dataset.issue));return;}const vf=e.target.closest('[data-view]');if(vf){setView(vf.dataset.view);return;}const sf=e.target.closest('[data-filter]');if(sf){setFilter(sf.dataset.filter);return;}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;const i=model.byId.get(selected);if(action==='close'){selected=null;focus=false;renderGraph();renderInspector();}else if(action==='focus'){focus=!focus;view='graph';renderGraph();renderInspector();fit();}else if(action==='copy'&&i){copy(promptFor(model,i,$('agent-name').value.trim()));}else if(action==='save'&&i){const agent=$('agent-name').value.trim();if(!agent){toast('请填写代理 / Worktree 名称');return;}assignments[i.number]={agent,note:$('agent-note').value.trim(),recordedAt:new Date().toISOString()};const saved=save(KEY+':assignments',assignments);renderStats();renderGraph();toast(saved?'已保存本机分配，不修改 GitHub':'浏览器禁止持久存储；当前页保留，关闭前请导出');}else if(action==='unassign'&&i){delete assignments[i.number];save(KEY+':assignments',assignments);render();toast('已清除本机分配');}});
document.addEventListener('keydown',e=>{const interactive=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(e.key==='Escape'&&!$('copy-dialog').open){selected=null;focus=false;renderGraph();renderInspector();}if(interactive)return;if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-issue]')){e.preventDefault();choose(e.target.dataset.issue);}if(e.key==='/'){e.preventDefault();$('search').focus();}if(e.key.toLowerCase()==='g')setView('graph');if(e.key.toLowerCase()==='l')setView('queue');});
$('search').addEventListener('input',e=>{search=e.target.value.trim().toLowerCase();renderGraph();});$('type-filter').addEventListener('change',e=>{typeFilter=e.target.value;renderGraph();});$('area-filter').addEventListener('change',e=>{areaFilter=e.target.value;renderGraph();});
$('clear-filters').onclick=()=>{statusFilter='';search='';typeFilter='';areaFilter='';focus=false;hideClosed=false;$('search').value='';$('toggle-completed').setAttribute('aria-pressed','false');render();};$('toggle-completed').onclick=()=>{hideClosed=!hideClosed;$('toggle-completed').setAttribute('aria-pressed',String(hideClosed));renderGraph();};
$('refresh').onclick=sync;$('copy-ready').onclick=()=>{const list=available();if(!list.length){toast('目前没有前置已满足且本机未分配的任务');return;}copy(`仓库：https://github.com/${REPO}\n数据快照：${snapshot?.fetchedAt}\n以下是前置已满足、未在本机分配的候选任务。可开始不等于可以无冲突并行；请核对文件范围并使用独立 worktree。\n\n`+list.map(i=>promptFor(model,i)).join('\n\n--------------------\n\n'));};
$('export-assignments').onclick=()=>{const blob=new Blob([JSON.stringify({repo:REPO,exportedAt:new Date().toISOString(),scope:'local-only',assignments},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='forguncy-agent-assignments.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('close-dialog').onclick=()=>$('copy-dialog').close();
$('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);$('fit').onclick=fit;$('reset-zoom').onclick=()=>{transform={x:12,y:15,scale:.88};setTransform();};
let drag=null;const graph=$('graph');graph.addEventListener('pointerdown',e=>{if(e.target.closest('[data-issue]'))return;drag={x:e.clientX,y:e.clientY,tx:transform.x,ty:transform.y};graph.setPointerCapture(e.pointerId);graph.classList.add('dragging');});graph.addEventListener('pointermove',e=>{if(!drag)return;transform.x=drag.tx+e.clientX-drag.x;transform.y=drag.ty+e.clientY-drag.y;setTransform();});for(const event of ['pointerup','pointercancel'])graph.addEventListener(event,()=>{drag=null;graph.classList.remove('dragging');});graph.addEventListener('wheel',e=>{e.preventDefault();const r=graph.getBoundingClientRect();if(e.ctrlKey||e.metaKey)zoom(Math.exp(-e.deltaY*.003),e.clientX-r.left,e.clientY-r.top);else{transform.x-=e.deltaX;transform.y-=e.deltaY;setTransform();}},{passive:false});
$('minimap').addEventListener('click',e=>{const svg=$('minimap'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const p2=p.matrixTransform(svg.getScreenCTM().inverse()),r=graph.getBoundingClientRect();transform.x=r.width/2-p2.x*transform.scale;transform.y=r.height/2-p2.y*transform.scale;setTransform();});
window.addEventListener('resize',()=>{setTransform();});
window.addEventListener('storage',e=>{if(e.key===KEY+':assignments'){assignments=load(KEY+':assignments',{});renderStats();renderGraph();renderInspector();}});
setInterval(()=>{if(!document.hidden){if(Date.now()>=nextAllowed)sync();renderSync();}},180000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(!snapshot||Date.now()-Date.parse(snapshot.fetchedAt)>180000))sync();});
if(window.innerWidth>760)selected=available()[0]?.number||null;
render();sync();
